### ISSUE TITLE
Assertion failed: (I <= this->end() && "Inserting past the end of the vector.")

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#101]
Trying to call a cheri_ccall or cheri_ccallee function crashes the compiler.

https://gist.github.com/brooksdavis/dfa552e939ea41fc1d25

```
/home/bed22/git/llvm-cheri/Build/bin/clang -integrated-as --target=cheri-unknown-freebsd -msoft-float --sysroot=/home/bed22/obj/mips.mips64/home/bed22/git/cheribsd/tmp -O -pipe -G0   -std=gnu99 -Wsystem-headers -Wall -Wno-format-y2k -W -Wno-unused-parameter -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wunused-parameter -Wcast-align -Wchar-subscripts -Winline -Wnested-externs -Wredundant-decls -Wold-style-definition -Wno-pointer-sign   -c /home/bed22/git/cheribsd/bin/cheri_helloworld/cheri_helloworld.c
Assertion failed: (I <= this->end() && "Inserting past the end of the vector."), function insert, file ../include/llvm/ADT/SmallVector.h, line 505.
clang-3.6: error: unable to execute command: Segmentation fault (core dumped)
clang-3.6: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.6.0 
Target: cheri-unknown-freebsd
Thread model: posix
clang-3.6: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3.6: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3.6: note: diagnostic msg: /tmp/cheri_helloworld-fa0054.c
clang-3.6: note: diagnostic msg: /tmp/cheri_helloworld-fa0054.sh
clang-3.6: note: diagnostic msg: 

********************
*** Error code 254
```

**Comment by davidchisnall** [comment]
This is a clang bug (fixed).  The code associated with the new call support is *very* light no error checking and still crashes with the attached code because of a bug in the code.  This line:

	struct hello_object;

Is a forward declaration of a struct type called hello_object, not a declaration of a variable to be the default class.  It needs to be:

	struct cheri_class hello_object;

To be used correctly (or `cheri_object` - as long as it's a struct that contains two capabilities, it should work).

**Comment by brooksdavis** [comment]
I've updated clang and fixed the declaration error and I'm still seeing the same assert failure.  https://gist.github.com/brooksdavis/22d2fe25e8a24c17b135

**Comment by davidchisnall** [comment]
Your file compiles for me:

	./cheri-unknown-freebsd-clang -msoft-float --sysroot=/home/bed22/obj/mips.mips64/home/bed22/git/cheribsd/tmp -O -pipe -G0   -std=gnu99 -Wsystem-headers -Wall -Wno-format-y2k -W -Wno-unused-parameter -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wunused-parameter -Wcast-align -Wchar-subscripts -Winline -Wnested-externs -Wredundant-decls -Wold-style-definition -Wno-pointer-sign -S -o - brooks/cheri_helloworld.c 

Output is: https://gist.github.com/davidchisnall/12e4d250f391f6af98b6

**Comment by brooksdavis** [comment]
I just did a clean build of llvm/clang and it's still failing for me.

**Comment by davidchisnall** [comment]
Looks like my git push failed.  Should be working now...
