### ISSUE TITLE
llvm does not understand mfc0 on cheri

### ISSUE THREAD

**Issue by rmn30** [CTSRD-CHERI/llvm#110]
llvm does not seem to know about the 32-bit move from co-processor instructions e.g.:
```
cheridis 0x401a6000
        .text
<stdin>:1:1: warning: invalid instruction encoding
0x40 0x1a 0x60 0x00
^
```
Which should decode as ` mfc0    k0,$12`.
The 64-bit `dmfc0` is supported e.g:
```
cheridis 0x402c3800
        .text
        dmfc0   $12, $7, 0
```

**Comment by davidchisnall** [comment]
Is this specific to CHERI-LLVM, or does it work with upstream LLVM?

**Comment by rmn30** [comment]
Sorry, I don't know how to test that.

**Comment by davidchisnall** [comment]
Try running the same llvm-mc line with upstream llvm...

**Comment by rmn30** [comment]
Apparently it works in upstream llvm. I ran this on vica:
```
 echo 0x40 0x1a 0x60 0x00 | /usr/local/bin/llvm-mc-devel -disassemble -triple=mips64-unknown-freebsd
        .text
        mfc0    $26, $12, 0
```

**Comment by rmn30** [comment]
Actually specifying the triple as mips64-unknown-freebsd will work in cheri-llvm too.

**Comment by brooksdavis** [comment]
Hitting this in the kernel's cpu.c.
