### ISSUE TITLE
.asciiz not implemented

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#113]
This can be solved by cherry picking llvm 203a9224ffb75cb50e6583303f705bf7173b9d99.  I've not done so to avoid creating conflicts with the cheri triple removal.

**Comment by davidchisnall** [comment]
Feel free to cherry pick things into master.  I need to rebase the other branch before merging it anyway.

**Comment by brooksdavis** [comment]
Merged in 87cdb5e40a1c477fb60c93cc6586a9143a094c2d
