### ISSUE TITLE
increment of __intcap_t

### ISSUE THREAD

**Issue by michael-roe** [CTSRD-CHERI/llvm#117]
The LLVM CHERI backend crashes if you try to increment an _intcap_t. Example C code:

static __intcap_t x;

int test()
{
        x = (__intcap_t) 1;
        x++;
        return 0;
}

***************

fatal error: error in backend: Cannot select: 0x8051f9aa0: iFATPTR = add
      0x8051f9440, 0x8051f9330 [ORD=5] [ID=15]
  0x8051f9440: iFATPTR = llvm.mips.cap.offset.set 0x8051f9000, 0x8051f9220, 0x8051f9330 [ORD=2] [ID=13]
    0x8051f9000: i64 = TargetConstant<1454> [ID=1]
    0x8051f9220: iFATPTR = INTTOPTR 0x8051f9110 [ID=10]
      0x8051f9110: i64 = Constant<0> [ID=2]
    0x8051f9330: i64 = Constant<1> [ID=3]
  0x8051f9330: i64 = Constant<1> [ID=3]
In function: test

********************

**Comment by davidchisnall** [comment]
Clang bug - assertions fail if built with a debug build.
