### ISSUE TITLE
ld internal error when compiling ntpdate with CheriABI

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/llvm#126]
Not quite clear where this bug report belongs, but we'll start with CHERI LLVM. If I mark CheriBSD's ntpdate(1) as being built with 256-bit CheriABI, then I get this linker error. Not clear if this is just an ld(1) bug, or if it is triggered by a bug in code generation on the LLVM side. This was generated by adding these lines to the usr.sbin/ntp/ntpdate Makefile:

+WENT_CHERI=pure
+WANT_DUMP=yes

CheriBSD version 9ed2a8738f5ed588f1316f098f08938f2b9b0816, CHERI LLVM version b5ef7b13d0e31e71683126844b9504e267153fac, CHERI Clang version 3da05ea3ad6db2e2d768f7fc72bcf5e6fa35ee14.

Output:

/home/rnw24/git/llvm/Build/bin/cheri-unknown-freebsd-clang -integrated-as --target=cheri-unknown-freebsd  -msoft-float --sysroot=/home/rnw24/obj/mips.mips64/home/rnw24/git/cheribsd/tmp -mabi=sandbox -O -pipe -G0   -I/home/rnw24/git/cheribsd/usr.sbin/ntp/ntpdate/../../../contrib/ntp/include  -I/home/rnw24/git/cheribsd/usr.sbin/ntp/ntpdate/../../../contrib/ntp/lib/isc/include/  -I/home/rnw24/git/cheribsd/usr.sbin/ntp/ntpdate/../../../contrib/ntp/lib/isc/unix/include/  -I/home/rnw24/git/cheribsd/usr.sbin/ntp/ntpdate/../../../contrib/ntp/lib/isc/pthreads/include  -I/home/rnw24/git/cheribsd/usr.sbin/ntp/ntpdate/../ -DSYS_FREEBSD -DPARSE -DHAVE_CONFIG_H  -DOPENSSL -DUSE_OPENSSL_CRYPTO_RAND -DAUTOKEY  -std=gnu99 -Wno-pointer-sign -Wno-empty-body -Wno-string-plus-int -Wno-unused-const-variable -Wno-tautological-compare -Wno-unused-value -Wno-parentheses-equality -Wno-unused-function -Wno-enum-conversion -Wno-unused-local-typedef -Wno-switch -Wno-switch-enum -Wno-knr-promoted-parameter -Wno-parentheses -Qunused-arguments  -Wl,--no-warn-mismatch -static -o ntpdate ntpdate.o version.o -L/home/rnw24/obj/mips.mips64/home/rnw24/git/cheribsd/usr.sbin/ntp/libntp -lntp  -lm   -lcrypto   -lpthread -lc -lmalloc_simple
/home/rnw24/obj/mips.mips64/home/rnw24/git/cheribsd/tmp/usr/bin/ld: BFD 2.17.50 [FreeBSD] 2007-07-03 assertion fail /home/rnw24/git/cheribsd/gnu/usr.bin/binutils/libbfd/../../../../contrib/binutils/bfd/elf64-mips.c:2297
/home/rnw24/obj/mips.mips64/home/rnw24/git/cheribsd/tmp/usr/bin/ld: BFD 2.17.50 [FreeBSD] 2007-07-03 internal error, aborting at /home/rnw24/git/cheribsd/gnu/usr.bin/binutils/libbfd/../../../../contrib/binutils/bfd/reloc.c line 445 in unsigned int bfd_get_reloc_size(reloc_howto_type *)

/home/rnw24/obj/mips.mips64/home/rnw24/git/cheribsd/tmp/usr/bin/ld: Please report this bug.

clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by davidchisnall** [comment]
I just set that flag and tried a buildworkd, and it passed for me.

**Comment by rwatson** [comment]
Your recent changes appear to have helped, although I'm not sure I can explain why. With the Clang update it went from "happening every build" to "not happening at all". So we can call it fixed and hope for the best!

**Comment by rwatson** [comment]
Bad news: due to user error, I was not compiling with WANT_CHERI, but rather, WENT_CHERI. In fact, the problem is still there for me once I spell WANT_CHERI more correctly. Given that I pasted the wrong thing above as well, you might retry with that as well. :-)

+WANT_CHERI=pure
+WANT_DUMP=yes

**Comment by davidchisnall** [comment]
We determined that this was caused by the fact that we're trying to link libpthread and we don't have a libpthread that works in CheriABI mode.

**Comment by brooksdavis** [comment]
This was actually due to PC32 relocations.  I've added support (which might work?) to binutils so now you get missing symbols due to a lack of a full malloc implementation and other things.
