### ISSUE TITLE
csc[bhwd] has swapped integer args relative to ISA

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#127]
The architecture guide says: CSCB rs, rd, cb
with rs in 16-20, rd in 6-10, and cb in 11-15, but rd is ending up in 6-10 and vise versa.  This might be a spec bug, hardware bug, or compiler bug.

**Comment by davidchisnall** [comment]
Are you looking at the latest spec?  I remember fixing this in the spec, but didn't commit an updated pdf.

**Comment by brooksdavis** [comment]
I thought I was as I'd done an svn update, but it turns out I wasn't.
