### ISSUE TITLE
cast<Ty>() argument of incompatible type

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#129]
Compiling this bit extracted from `contrib/compiler-rt/lib/builtins/enable_execute_stack.c` fails as shown.  The actual code is nonsense for CheriABI since we can't just go making the stack executable with `mprotect`, but this should either work or fail with a useful error.

```c
extern __uintcap_t pageAlignMax;

void
foo(void)
{
        __uintcap_t pageSize = 4096;
        pageAlignMax = ~(pageSize - 1);
}
```

```
$ clang -integrated-as --target=cheri-unknown-freebsd  -msoft-float -mabi=sandbox -c foo.c
Assertion failed: (isa<X>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file ../include/llvm/Support/Casting.h, line 237.
clang-3.6: error: unable to execute command: Segmentation fault (core dumped)
clang-3.6: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.7.0 (https://github.com/llvm-mirror/clang.git 41a3277b6fefcf99157d95920e67803a6693e522) (https://github.com/llvm-mirror/llvm.git 7c040e854fb369549dc27eac97d6b58c38f705df)
Target: cheri-unknown-freebsd
Thread model: posix
clang-3.6: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3.6: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3.6: note: diagnostic msg: /tmp/foo-690701.c
clang-3.6: note: diagnostic msg: /tmp/foo-690701.sh
clang-3.6: note: diagnostic msg: 

********************
```

**Comment by davidchisnall** [comment]
It looks as if there are still some operations where `[u]intcap_t` isn't doing the right thing.  It would help if you could put together a single test case that has all of the C operators applied to these two types.

**Comment by brooksdavis** [comment]
I've committed such a test as CTSRD-CHERI/cheri-c-tests@23b329027895c748ac1a0c5432d151a610b9ec10.  It reveals both compile time and runtime bugs.

**Comment by davidchisnall** [comment]
I meant as clang tests.  Unfortunately, the license on the C test suite test means that I can't use it in the clang test suite.

**Comment by brooksdavis** [comment]
If you point me to an example I'll work one up and commit it after your upstream merge.

**Comment by davidchisnall** [comment]
Here is one: https://github.com/CTSRD-CHERI/clang/blob/master/test/CodeGen/intcap_t.c

**Comment by davidchisnall** [comment]
Fixed (clang bug)
