### ISSUE TITLE
Inliner is disabled in the sandbox ABI

### ISSUE THREAD

**Issue by davidchisnall** [CTSRD-CHERI/llvm#131]
The current lowering of calls in CHERI-clang turns direct calls into calls of an expression that is the result of arithmetic on PCC.  The inliner doesn't recognise them as potential inlining targets.

The correct fix is probably to defer some of this to a pre-codegen pass so that the IR fed to the optimisers looks a bit more normal.

**Comment by davidchisnall** [comment]
This was fixed in c1d40a2

**Comment by arichardson** [comment]
This is broken again with cap-table since LLVM doesn't understand how to inline AS200 call instructions.

**Comment by arichardson** [comment]
Reopened the wrong bug. It's only always_inline at -O0 that's broken
