### ISSUE TITLE
printf format checker things intptr_t is a long in sandbox ABI mode

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#136]
I committed some new failing tests in CTSRD-CHERI/clang@139ee891f4e1a059b7816f0679cb12580bf325ba where the compiler thinks `intptr_t` should be a `long`.  Tracking back through the code it looks like this is actually a Target issue and is fallout from bfa6cd4fc9284bd016117cbf49212876781a6d43 which causes the implementation of `DataLayout::getIntPtrType()` to think `intptr_t` is of type `long`.

**Comment by davidchisnall** [comment]
That diagnosis sounds unlikely, as `DataLayout` doesn't know about C-level types.  I'll take a look.

**Comment by davidchisnall** [comment]
Clang bug.  Fixed in CTSRD-CHERI/clang@f8e70c5.
