### ISSUE TITLE
CheriABI cheriabitest: generated code uses uninitialised register in constructor function

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/llvm#146]
Using ```cheriabitest```, and in-progress compilation of ```cheritest``` intended to run under CheriABI, I see the following surprising code generated for the function ```sandbox_stat_init```, a constructor. $t9 is derived from $c12 using CGetOffset, but $c12 has not previously been set in the function, nor is a defined argument (as there are no arguments to the function):
```
000000012006a270 <sandbox_stat_init>:
static struct sandbox_object_stat
    sandbox_object_stats[SANDBOX_OBJECT_STAT_MAX];

__attribute__ ((constructor)) static void
sandbox_stat_init(void)
{
   12006a270:   67bdfee0        daddiu  sp,sp,-288
   12006a274:   67a50118        daddiu  a1,sp,280
   12006a278:   ebcb2803        csd     s8,a1,0(c11)
   12006a27c:   fa2be8e0        csc     c17,sp,224(c11)
   12006a280:   03a0f025        move    s8,sp
   12006a284:   49b96002        cgetoffset      t9,c12            <--- $t9 is derived from uninitialised $c12
   12006a288:   3c01000f        lui     at,0xf
   12006a28c:   0039082d        daddu   at,at,t9
   12006a290:   64215c50        daddiu  at,at,23632
   12006a294:   67d900c0        daddiu  t9,s8,192
   12006a298:   49ac5e41        csetoffset      c12,c11,t9       <-- .. something about the stack?
   12006a29c:   64190020        daddiu  t9,zero,32
   12006a2a0:   482c6640        csetbounds      c12,c12,t9
   12006a2a4:   67d900b8        daddiu  t9,s8,184
   12006a2a8:   49a15e41        csetoffset      c1,c11,t9
   12006a2ac:   64190008        daddiu  t9,zero,8
   12006a2b0:   48210e40        csetbounds      c1,c1,t9
   12006a2b4:   67c200b0        daddiu  v0,s8,176
   12006a2b8:   49a25881        csetoffset      c2,c11,v0
   12006a2bc:   48221640        csetbounds      c2,c2,t9
   12006a2c0:   64040000        daddiu  a0,zero,0
        struct ps_strings *ps_strings;
        unsigned long ul_ps_strings;
        size_t len;

        len = sizeof(ul_ps_strings);
   12006a2c4:   eb220003        csd     t9,zero,0(c2)
   12006a2c4:   eb220003        csd     t9,zero,0(c2)
        if (sysctlbyname("kern.ps_strings", &ul_ps_strings, &len, NULL, 0)
   12006a2c8:   3c020000        lui     v0,0x0
   12006a2cc:   0041102d        daddu   v0,v0,at
   12006a2d0:   dc42ab58        ld      v0,-21672(v0)
   12006a2d4:   48001807        cgetpcc c3
   12006a2d8:   49a31881        csetoffset      c3,c3,v0
   12006a2dc:   3c020000        lui     v0,0x0
   12006a2e0:   0041102d        daddu   v0,v0,at
   12006a2e4:   dc4295c8        ld      v0,-27192(v0)
   12006a2e8:   48840087        cfromptr        c4,c0,v0
   12006a2ec:   48860007        cfromptr        c6,c0,zero
   12006a2f0:   f86bf080        csc     c3,s8,128(c11)
   12006a2f4:   49a32000        cmove   c3,c4
   12006a2f8:   49a40800        cmove   c4,c1
   12006a2fc:   49a51000        cmove   c5,c2
   12006a300:   d84bf080        clc     c2,s8,128(c11)
   12006a304:   f98bf060        csc     c12,s8,96(c11)          <-- eventually ends up on the stack to use later
```

Later on, the program crashes as a result of dereferencing $c12.

**Comment by davidchisnall** [comment]
`$c12` is defined by the calling convention as the register that contains the capability to the function (i.e. $pcc with the offset set to the function entry point).  The code calling this is probably not doing the right thing - there's a macro somewhere that lets you do a call setting both `$c12` and `$t9` to the correct values (`abicall.s`, I think?) in asm code that needs to be compatible with both calling conventions.

**Comment by rwatson** [comment]
Indeed -- and it looks like there's a later integer-to-pointer cast that was likely triggering the problem.

**Comment by davidchisnall** [comment]
Hmm, the actual define of `$t9` before that is

```
daddiu  t9,s8,192
```

`s8` is normally called `$fp`.  The `$c12` that's derived from `$c11` is a normal 32-byte stack allocation. This looks like a normal stack allocation of 32 bytes (32-byte aligned, assuming that .the stack is correctly aligned).

**Comment by rwatson** [comment]
Yes, I no longer think there is a problem with the code generated here -- the issue turned out to be yet another integer-constant/source-to-pointer cast -- in this case for a value coming back from ```sysctl``` (```ps_strings```). I've had to fix about half a dozen (maybe more) of those in ```libcheri``` to get ```cheriabitest``` working thus far. As this is, effectively, a run-time linker, it's probably a special case and we shouldn't (yet) worry. If we discover much other code needs this, we might need to ponder some more.
