### ISSUE TITLE
clang running forever

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#150]
One of the changes in the last push is causing clang to run for a very long time (over 800 minutes in a case running in the clang tests under jenkins).  I've also observed hangs building CheriBSD.

**Comment by davidchisnall** [comment]
Do you have an example file that demonstrates the behaviour?  I did several buildworlds while testing these changes and did not see this.

**Comment by rwatson** [comment]
I have also encountered this .. but only sometimes. My ```build_sdk.sh``` run last night saw it, but rerunning this morning didn't. It's unclear to me what is triggering this.

**Comment by brooksdavis** [comment]
I'm seeing the hang reliably with strtol_c.c in libc.

**Comment by brooksdavis** [comment]
It looks like it has been fixed.
