### ISSUE TITLE
Miscomputation in zlib inflate and deflate code in pure-capability ABI when compiled with -O2 (but work at -O0 and -O1)

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/llvm#155]
Currently, two uncompartmentalised ```zlib``` test cases pass in ```cheritest```, but fail in ```cheriabitest```, which likely also explains why the compartmentalised ```zlib``` test case also fails. The failure occurs both in CHERI hardware and on Qemu, so is most likely a code-generation problem with the pure-capability case. The tests both pass at ```-O0``` and ```-O1```, but not at ```-O2```.

Output from Qemu using a ```-O2``` world:
```
root@qemu-cheri:~ # cheritest test_inflate_zeroes test_deflate_zeroes
TEST: test_inflate_zeroes: Inflate a compressed buffer of zeroes
PASS: test_inflate_zeroes
TEST: test_deflate_zeroes: Deflate a buffer of zeroes
PASS: test_deflate_zeroes
SUMMARY: passed 2 failed 0
root@qemu-cheri:~ # cheriabitest test_inflate_zeroes test_deflate_zeroes
TEST: test_inflate_zeroes: Inflate a compressed buffer of zeroes
FAIL: test_inflate_zeroes: inflate returned -3
TEST: test_deflate_zeroes: Deflate a buffer of zeroes
FAIL: test_deflate_zeroes: compressed data length wrong (expected 33, got 11)
SUMMARY: passed 0 failed 2
```

Output from Qemu using a ```-O1``` world:
```
root@qemu-cheri:~ # cheritest test_inflate_zeroes test_deflate_zeroes
TEST: test_inflate_zeroes: Inflate a compressed buffer of zeroes
PASS: test_inflate_zeroes
TEST: test_deflate_zeroes: Deflate a buffer of zeroes
PASS: test_deflate_zeroes
SUMMARY: passed 2 failed 0
root@qemu-cheri:~ # cheriabitest test_inflate_zeroes test_deflate_zeroes
TEST: test_inflate_zeroes: Inflate a compressed buffer of zeroes
PASS: test_inflate_zeroes
TEST: test_deflate_zeroes: Deflate a buffer of zeroes
PASS: test_deflate_zeroes
SUMMARY: passed 2 failed 0
```

Output from Qemu using a ```-O0``` world:
```
root@qemu-cheri:~ # cheritest test_inflate_zeroes test_deflate_zeroes
TEST: test_inflate_zeroes: Inflate a compressed buffer of zeroes
PASS: test_inflate_zeroes
TEST: test_deflate_zeroes: Deflate a buffer of zeroes
PASS: test_deflate_zeroes
SUMMARY: passed 2 failed 0
root@qemu-cheri:~ # cheriabitest test_inflate_zeroes test_deflate_zeroes
TEST: test_inflate_zeroes: Inflate a compressed buffer of zeroes
PASS: test_inflate_zeroes
TEST: test_deflate_zeroes: Deflate a buffer of zeroes
PASS: test_deflate_zeroes
SUMMARY: passed 2 failed 0
```

The ```inflate``` and ```deflate``` tests are independent of each other: the former works from a regenerated compressed data set compiled into the binary rather than depending on compression during the test case, and the latter attempts to compress a buffer of zeroes. It is unclear if the two failures relate to one another or not, but the coding style and idioms are similar to one another so they might well do.

**Comment by davidchisnall** [comment]
Compiling everything at -O2 doesn't do much to narrow down where the miscompilation is.  Does it work if world is -O2 but this test is at -O1?

**Comment by rwatson** [comment]
If I recompile ```libz```'s ```inflate.c``` with ```-O1``` (leaving the rest of ```world```, including the rest of ```libz```, as ```-O2```), the inflate test passes.

(Still testing deflate cases.)

**Comment by rwatson** [comment]
If I recompile ```libz```'s ```deflate.c``` with ```-O1``` (leaving the rest of ```world``` as ```-O2```), the deflate test still fails, but gives a slightly different error:
```
TEST: test_deflate_zeroes: Deflate a buffer of zeroes
FAIL: test_deflate_zeroes: compressed data length wrong (expected 33, got 43)
```

If I further recompile ```libz```'s ```trees.c```, then both tests pass:
```
root@qemu-cheri:~ # cheriabitest test_inflate_zeroes test_deflate_zeroes
TEST: test_inflate_zeroes: Inflate a compressed buffer of zeroes
PASS: test_inflate_zeroes
TEST: test_deflate_zeroes: Deflate a buffer of zeroes
PASS: test_deflate_zeroes
SUMMARY: passed 2 failed 0
```

So on face value, it appears both tests fail due to problems compiling elements of ```libz``` at ```-O2```.

**Comment by rwatson** [comment]
The attached test program may be useful in reproducing the problem(s):

https://gist.github.com/rwatson/339733c4289a952d3183a66d2373b722

**Comment by davidchisnall** [comment]
This appears to be another GVN issue, though tracking it down is proving difficult.

**Comment by davidchisnall** [comment]
It appears that there are at least two GVN issues here.  Something in `GVN::PerformLoadPRE` is breaking `trees.c`, something else is breaking `inflate.c`.

**Comment by davidchisnall** [comment]
On further investigation, GVN is performing the transform in different places but they appear to be triggered by the same analysis bug (or, at the very least, two very similar ones).
