### ISSUE TITLE
assembler support for function pointers

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#163]
In MIPS64 code, calling a function is:
```asm
dla t9, _C_LABEL(__error)
jalr r9
nop
```

In static cheri code it's fairly easy to call a function.  You do something like the following which is ok:
```asm
dla          t9, _C_LABEL(__error)
cgetpccsetoffset      $c12, $c12, t9
cjalr           $c17, $c12
nop
```

In PIC code, it's rather messier:
```asm
        dla             t0, 1f
1:     cgetpcc         $c12
        cgetoffset      t1, $c12
        dsub            t0, t1, t0
        csetoffset      $c12, $c12, t0
        dla             t9, _C_LABEL(__error)
        cincoffset      $c12, $c12, t9
        cjalr           $c17, $c12
        nop
```

It would be nice if there was a pseudo for "make me a function pointer capability for this label".  Eventually we'll be able to simplify this a bit when we start requiring for PCC to be constrained to the actually excitable code, but that's for later.

**Comment by brooksdavis** [comment]
Hmm, now that I think about it, we could a probably should use a macro for this.

**Comment by davidchisnall** [comment]
Most of the complexity comes from the FreeBSD macros.  The use of the `dla` pseudo also causes some confusion.  The canonical sequence for a call in PIC pure-capability ABI code is in three parts.  

First the GOT setup, which should be in the function prolog.  FreeBSD has some macros that do the right thing for n64, but I don't know if they've been implemented for the pure-cap ABI.  The only difference currently is the first line:

```asm
	cgetoffset	$25, $c12  ; Get the PCC offset on entry to the function
	lui	$1, %hi(%neg(%gp_rel(current_function)))
	daddu	$1, $1, $25
	daddiu	$gp, $1, %lo(%neg(%gp_rel(current_function)))
```

At the end of this, `$gp` contains the `$c0`-relative offset of GOT.  Then you must load the function pointer from the GOT:

```asm
	daddiu	$1, $gp, %call16(a)
	cfromptr	$c1, $c0, $1
	cld	        $1, $zero, 0($c1)
```

Now construct and call the code capability:

```asm
	cgetpccsetoffset	$c12, $1
	cjalr	           $c17, $c12
	nop ; delay slot, other stuff can go here if you want
```

Note that the operand order of `cjalr` is wrong (i.e. the opposite order to every other `jalr`-like instruction on every other platform, including MIPS).  This is something that I'd like to fix once the fallout from the current flag day has settled.
