### ISSUE TITLE
Comparing weak symbols to NULL always returns false

### ISSUE THREAD

**Issue by RichardsonAlex** [CTSRD-CHERI/llvm#167]
I have the following code inside CHERIBSD/lib/thr/thread/thr_exit.c which will always crash due to trying to call null pointer:
```c
#pragma weak _Unwind_ForcedUnwind
// ....
if (_Unwind_ForcedUnwind != NULL) {
    //  ...
    _Unwind_ForcedUnwind(&curthread->ex, thread_unwind_stop, NULL);
}
```

This gets compiled into the following assembly:
```
   12000d89c:	48950007 	cfromptr	c21,c0,zero
   # ...
   12000d96c:	3c010000 	lui	at,0x0
   12000d970:	003c082d 	daddu	at,at,gp
   12000d974:	dc21c1f8 	ld	at,-15880(at)
   12000d978:	480107ff 	cgetpcc	c1
   12000d97c:	49a10841 	csetoffset	c1,c1,at
   12000d980:	49c10d40 	ceq	at,c1,c21
   12000d984:	1420002c 	bnez	at,12000da38 <_pthread_exit_mask+0x228>
   # ...
```

The resulting value of `_Unwind_ForcedUnwind` is `0x0{v:1 s:0 p:7fff8017 b:0 l:10000000000 o:0 t:0}`. which does not compare equal to NULL.
The objdump symbol table show that _Unwind_ForcedUnwind is undefined: `0000000000000000  w    F *UND*	0000000000000000 _Unwind_ForcedUnwind`

I'm not sure if this only applies to weak symbols or also other function pointers.

**Comment by davidchisnall** [comment]
Clang bug.  Fixed in CTSRD-CHERI/clang@908bc7f
