### ISSUE TITLE
ASM macro max nest-level is low

### ISSUE THREAD

**Issue by hbcam** [CTSRD-CHERI/llvm#171]
I hit this limit using a recursive macro: `error: macros cannot be nested more than 20 levels deep`

This seems quite low.

Pull request #170 increases it.

**Comment by davidchisnall** [comment]
20 seems pretty high.  What are you doing that has more than 20 levels of nested macros?

**Comment by hbcam** [comment]
New pull request in #178.

**Comment by hbcam** [comment]
Done in 87ee11210d48f2c8e976ca61d80014e148c801f8.
