### ISSUE TITLE
When compiled with optimisation, getpwuid(3) and getpwnam(3) fail

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/llvm#172]
SSH (and other base-system software) fails to look up users and UIDs using ```libc``` APIs ```getpwnam(3)``` and ```getpwuid(3)``` when compiled with optimisation:
```
> ./ssh localhost
No user exists for uid 999
```

A simple test program executed on either Qemu or FPGA illustrates the ```getpwuid(3)``` failure:
```
#include <sys/types.h>

#include <errno.h>
#include <pwd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int
main(int argc, char *argv[])
{
        struct passwd *pwd;
        int i, errno;

        for (i = 1; i < argc; i++) {
                errno = 0;
                pwd = getpwuid(atoi(argv[i]));
                if (pwd == NULL && errno == 0)
                        printf("%s: not found\n", argv[i]);
                else if (pwd == NULL)
                        printf("%s: errno %d (%s)\n", argv[i], errno,
                            strerror(errno));
                else
                        printf("%s: %s\n", argv[i], pwd->pw_name);
        }
        return (0);
}
```

With the library and program compiled with ```-O0```, the results are desirable:
```
root@:~ # getpwuid 0
0: root
```

With ```-O```, incorrect:
```
root@:~ # getpwuid 0
0: not found
```

With ```-O1```, incorrect:
```
root@:~ # getpwuid 0
0: not found
```

With ```-O2```, incorrect:
```
root@:~# getpwuid 0
0: not found
```

A casual investigation using an ISA-level trace suggests ```compat_passwd()``` is failing part way through execution, returning an error. It could be that this is occurring in the ```db/hash``` code, but I've not yet been able to confirm that.

**Comment by rwatson** [comment]
A system call trace suggests that the password file is opened and read before a problem arises accessing the data.

**Comment by davidchisnall** [comment]
When I run it, the test program takes about 5 minutes and then prints `MMMMMMMM`.

**Comment by rwatson** [comment]
FYI, here is the ```Makefile``` I built it with:
```
# $FreeBSD$

PROG=   getpwuid

MAN=
NEED_CHERI=     pure
WANT_DUMP=      yes

NO_SHARED?=     YES

NO_WERROR=      YES

.include <bsd.prog.mk>
```

Do make sure you're testing statically linked; I've not yet tried it dynamically linked and do not expect particularly better behaviour.

**Comment by davidchisnall** [comment]
Turning off optimisation in `compat_passwd` makes the test pass, so it looks as if something in that function is being incorrectly optimised.

**Comment by davidchisnall** [comment]
It's quite difficult to track down a compiler bug when the test case is barely comprehensible spaghetti code that takes 5 minutes to compile.  I don't suppose you've got a reduced test for this (or something that doesn't require I/O so I can try reducing it)?

**Comment by rwatson** [comment]
Unfortunately, no. I prodded away at test-case reduction for much of Sunday without any luck after chasing the failure in SSH down to this, and have had to context switch to other things. It looks like the code up until the ```pread(2)``` may be working fine (i.e., execution is not visibly wrong before then as it opens the correct file, etc) -- I wonder if there's an easy path to feed a copy of ```spwd.db``` or ```pwd.db``` into the DB code without the file I/O -- e.g., to embed its contents in a .C file. It looks like ```pread(2)``` is used exactly twice on the path to failure, both times on the same file (presumably the password file) when the binary is statically linked. (If dynamically linked, I know that ```rtld``` quite likes ```pread(2)``` as well.)

**Comment by rwatson** [comment]
Just for reference, since I had the output handy anyway:
```
> kdump | grep pread
  4362 getpwuid CALL  pread(0x3,0x49a000,0x1000,0x6000)
  4362 getpwuid RET   pread 4096/0x1000
  4362 getpwuid CALL  pread(0x3,0x49b000,0x1000,0x4000)
  4362 getpwuid RET   pread 4096/0x1000
```

(Which is a very slightly odd sequence, but whatever.)

**Comment by davidchisnall** [comment]
It looks as if the behaviour of the n64 / CheriABI versions diverge at this line:
```
rv = st->db->get(st->db, &key, &entry, 0);
```
This returns 1 for CheriABI and 0 for n64 code.

**Comment by davidchisnall** [comment]
Are you sure that this works in qemu?  I've simplified the function and I still have a failing case, but it looks like it might be a hardware issue.  This is the code for setting up the arguments:

```assembly
          clw       $1, $zero, 32($c24) # Load the value from st->keynum (htonl is a nop)
          csw       $1, $zero, 1($c19) # Store it (1 as a 32-bit quantity) in &keybuf[1]
          daddiu    $1, $zero, 5       # Do some weird stuff in a macro
          csd       $1, $zero, 32($c21)
          clw       $1, $zero, 40($c24)
          sll       $1, $1, 4
          ori       $1, $1, 2
          sll       $1, $1, 0
          csb       $1, $zero, 0($c19) # Store the result (0x42) in &keybuf[0]
```

When I get inside the `hash_get` function, I've added this debugging code:

```C
fprintf(stderr, "Calling hash-get with key: (0x%hhx) 0x%x (%d)\n", *(char*)key->data, *(unsigned int*     )((char*)key->data+1), (int)key->size);
```

In the n64 version, it prints this:
```
Calling hash-get with key: (0x42) 0x1 (5)
```

In the CheriABI version, I get this:

```
Calling hash-get with key: (0x42) 0x42000001 (5)
```

It looks as if, in the CheriABI case, the `csb` is overwriting the second byte of the 5-byte array.  It looks as if something might be wrong with the merging of unaligned values?  In the CHERI case, the array is 4-byte aligned, whereas in the MIPS case it is 32-byte aligned, but we're doing an unaligned store / load in both cases.

**Comment by rwatson** [comment]
At least for me, the above ```getpwuid``` test runs successfully as a CheriABI binary on Qemu (for me). As Qemu is a moving target, and to be clear: I'm using a33b3a191ccadab8dca93e3e28250633370c1271, which suffers a problem with surprising tags, but appears to generate the output above (e.g., turning UID 0 into ```root```) when compiled without optimisation.

**Comment by davidchisnall** [comment]
@jonwoodruff points out that `csw       $1, $zero, 1($c19)` is not a legal instruction.  We're somehow generating an instruction with an illegal offset.

**Comment by davidchisnall** [comment]
Test case that shows the bug:

```C
void * memcpy(void *restrict dst, const void *restrict src, unsigned long n);

void foo(char *b);

void bar(int x)
{
	char buffer[5];
	memcpy(&buffer[1], &x, sizeof(int));
	foo(buffer);
}
```

Generates:

```asm
	csw	$4, $zero, 1($c3)
```

Which is illegal.  It appears to be caused by the addressing mode folder, which apparently wasn't correctly updated for the scaled immediates.  Sorry for extending the flag-time-unit...

**Comment by rwatson** [comment]
Just to confirm: I think ```gas``` is now properly checking for invalid immediates on capability-relative load/store. I was sure ```llvm-as``` was as well (and likely better), but I guess there is a gap in validation here...?

**Comment by davidchisnall** [comment]
Yes, the assembler was checking the constraints and the constraints were used in lowering from SelectionDAG.  The problem was that there is no checking when you modify the constraints manually, as the addressing modes pass did.
