### ISSUE TITLE
getpwuid test program incorrectly always returns information for only the root user

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/llvm#173]
#172 reported a bug in which ```getpwuid(3)``` failed to return any user description for a UID passed on the command line, even when valid; with its fix, a user structure will now be returned when a UID is looked up. This issue reports a bug in which ```getpwuid(3)``` always returns the root-user description, even if another UID is requested, even an invalid one. The same test program is used, without modification, but with different command-line arguments. The following UIDs are defined in the password files for these tests: 0 (root), 2 (operator), and 10000 (no user). All tests are performed with a statically linked, pure-capability binary on Qemu-CHERI using a compiler that includes the fix to #172. Optimisation levels below are with respect to a full CheriBSD build including the ```getpwuid``` binary. (These results would seem to suggest a problem with key comparison -- but one can certainly imagine any other potential pointer-related nastinesses in processing DB entries.) A further and possibly unrelated complication is a compilation failure building at -O1 (to be reported separately).

With -O0:
```
root@:~ # getpwuid 0
0: root
root@:~ # getpwuid 2
2: operator
root@:~ # getpwuid 10000
10000: not found
```

With -O1: (build failure)

With -O2:
```
root@:~ # getpwuid 0
0: root
root@:~ # getpwuid 2
2: root
root@:~ # getpwuid 10000
10000: root
```

For reference, on x86-64:
```
[rnw24@vica ~/git/qemu]$ ~/git/cheribsd/bin/getpwuid/getpwuid.x86 0
0: root
[rnw24@vica ~/git/qemu]$ ~/git/cheribsd/bin/getpwuid/getpwuid.x86 2
2: operator
[rnw24@vica ~/git/qemu]$ ~/git/cheribsd/bin/getpwuid/getpwuid.x86 10000
10000: not found
```

**Comment by davidchisnall** [comment]
Did you look at the console while the test was running?  When I run it, I get a number of unaligned store warnings:

```
Unaligned Capability Store Word: pid=1573 (a.out), tid=100415, pc=0x12001f5a4, badvaddr=0x7fffffd65d
Unaligned Capability Store Word: pid=1573 (a.out), tid=100415, pc=0x12001f5a4, badvaddr=0x7fffffd65d
Unaligned Capability Store Word: pid=1573 (a.out), tid=100415, pc=0x12001f5a4, badvaddr=0x7fffffd65d
Unaligned Capability Store Word: pid=1573 (a.out), tid=100415, pc=0x12001f5a4, badvaddr=0x7fffffd65d
```

If the kernel is not correctly emulating the `csw` for unaligned stores, then this may account for the error.

**Comment by rwatson** [comment]
I was running on the console and did not see these errors. Are you running on Qemu or a bitfile? The former could have stronger (but perhaps less correct?) unaligned access semantics than the latter?

**Comment by rwatson** [comment]
Adding @staceyson as I'm not sure to what extent our ISA-level test suite covers edge cases in capability-relative unaligned access.

I will rerun tests with the ```-O2``` version on both Qemu and the bitfile and re-check whether unaligned accesses arise.

**Comment by rwatson** [comment]
(Also adding @michael-roe as he might comment on the degree to which we test unaligned access at the ISA level.)

**Comment by davidchisnall** [comment]
It appears that, now, `getpwuid_r` works correctly, however `getpwuid` does not.  The following test program illustrates the difference:

```C
#include <sys/types.h>

#include <errno.h>
#include <pwd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int
main(int argc, char *argv[])
{
        struct passwd *pwd;
        int i, errno;

        errno = 0;
        struct passwd pw;
        const size_t buffer_size = 513;
        char buffer[buffer_size];
        for (int i=0 ; i<1024 ; i++)
        {
            struct passwd *pwo = getpwuid(i);
            getpwuid_r(i, &pw, buffer, buffer_size, &pwd);
            if ((pwo == NULL) && (pwd == NULL))
                continue;
            if ((pwo == NULL) || (pwd == NULL))
            {
                printf("getpwuid: %s, getpwuid_r: %s\n", pwo ? pwo->pw_name : 0, pwd ? pwd->pw_name : 0);
            }
            else if (strcmp(pwd->pw_name, pwo->pw_name) != 0)
            {
                printf("getpwuid: %s, getpwuid_r: %s\n", pwo->pw_name, pwd->pw_name);
            }
            else if (pwd != NULL)
                    printf("%d: %s\n", i, pwd->pw_name);
        }
        return (0);
}
```

This correctly shows the UID to username mappings when calling `getpwuid_r`, but not when calling `getpwuid`.

**Comment by davidchisnall** [comment]
It looks as if this might be related to the `wrap_getpwuid_r` function.  This takes a `union key`, which contains integer and capability values, and passes it to a function that expects an integer.  The wrap function is always passing 0 in `$a0`, rather than storing the capability to memory and loading the integer value back.  This implies that an optimiser is doing something bad.

**Comment by davidchisnall** [comment]
And, what a surprise, it's *another* GVN issue:

```
; Function Attrs: nounwind
define i32 @bar(i8 addrspace(200)* inreg %u.coerce) #0 {
entry:
  %u.sroa.0.sroa.0 = alloca i8 addrspace(200)*, align 32
  store i8 addrspace(200)* %u.coerce, i8 addrspace(200)* addrspace(200)* %u.sroa.0.sroa.0, align 32
  %u.sroa.0.sroa.0.0.x.sroa_cast2 = bitcast i8 addrspace(200)* addrspace(200)* %u.sroa.0.sroa.0 to i32 addrspace(200)*
  %u.sroa.0.sroa.0.0.u.sroa.0.sroa.0.0.u.sroa.0.0.u.sroa.0.0. = load i32, i32 addrspace(200)* %u.sroa.0.sroa.0.0.x.sroa_cast2, align 32
  %call = tail call i32 @foo(i32 signext %u.sroa.0.sroa.0.0.u.sroa.0.sroa.0.0.u.sroa.0.0.u.sroa.0.0.) #3
  ret i32 %call
}
*** IR Dump After Global Value Numbering ***
; Function Attrs: nounwind
define i32 @bar(i8 addrspace(200)* inreg %u.coerce) #0 {
entry:
  %u.sroa.0.sroa.0 = alloca i8 addrspace(200)*, align 32
  store i8 addrspace(200)* %u.coerce, i8 addrspace(200)* addrspace(200)* %u.sroa.0.sroa.0, align 32
  %u.sroa.0.sroa.0.0.x.sroa_cast2 = bitcast i8 addrspace(200)* addrspace(200)* %u.sroa.0.sroa.0 to i32 addrspace(200)*
  %0 = ptrtoint i8 addrspace(200)* %u.coerce to i64
  %call = tail call i32 @foo(i32 signext undef) #3
  ret i32 %call
}
```
