### ISSUE TITLE
capsizefix fails to identify syscall assembly as functions

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#182]
The system call interposition table in CheriBSD's libc is a table of pointers to system call functions, by default actually call in assembly of the form `__sys_openat`.  Capability relocation table entries are properly created for them, but `capsizefix` fails to recognize that they are functions.  If I declare a C wrapper and assign that it does the right thing, but that's an ugly option.  Example wrapper:

``` C
int ___sys_openat(int fd, const char *path, int flags, mode_t mode);
int
___sys_openat(int fd, const char *path, int flags, mode_t mode)
{

        return (__sys_openat(fd, path, flags, mode));                            }
```

The implementation of `__sys_openat` is through a bunch of pre-processor macros that expand to:

```
.globl __sys_openat;
.ent __sys_openat;
.type __sys_openat,@function;
__sys_openat: ;
.frame $29, 0, $31;
;
.weak _openat;
_openat = __sys_openat;
;
li $2,499; syscall;
;
bne $7,$0,err;
cjr $c17;
err: j __cerror;
.end __sys_openat
```

**Comment by brooksdavis** [comment]
@bsdjhb thinks this issue in this commit might be the underlying issue.   https://github.com/illumos/illumos-gate/commit/e111a5f95e36165858dd4f04101c60e8c5badaa3

I'm not sure if fixing detection of symbol types is really the right approach.  It might be that we want to generate a separate array for function pointers since we know they are function pointers in the compiler.  That would avoid having to infer the type from the symbol.

**Comment by arichardson** [comment]
capsizefix is obsolete
