### ISSUE TITLE
Some bitfield accesses crash the CHERI MIPS backend

### ISSUE THREAD

**Issue by michael-roe** [CTSRD-CHERI/llvm#189]
Example program:

struct foo {
  unsigned a:32;
  unsigned b:32;
  unsigned c:32;
  unsigned d:31;
  unsigned e:1;
};

static struct foo x;

int main(int argc, char **argv)
{
  x.d = 1;
  return 0;
}

/************************/

; ModuleID = 'test_pack.c'
target datalayout = "E-m:m-pf200:256:256-i8:8:32-i16:16:32-i64:64-n32:64-S128-A200"
target triple = "cheri-unknown-freebsd"

%struct.foo = type { i128 }

@x = internal addrspace(200) global %struct.foo zeroinitializer, align 4

; Function Attrs: nounwind
define i32 @main(i32 signext %argc, i8 addrspace(200)* addrspace(200)* %argv) #0 {
  %1 = alloca i32, align 4
  %2 = alloca i32, align 4
  %3 = alloca i8 addrspace(200)* addrspace(200)*, align 32
  store i32 0, i32 addrspace(200)* %1, align 4
  store i32 %argc, i32 addrspace(200)* %2, align 4
  store i8 addrspace(200)* addrspace(200)* %argv, i8 addrspace(200)* addrspace(200)* addrspace(200)* %3, align 32
  %4 = load i128, i128 addrspace(200)* getelementptr inbounds (%struct.foo, %struct.foo addrspace(200)* @x, i32 0, i32 0), align 4
  %5 = and i128 %4, -4294967295
  %6 = or i128 %5, 2
  store i128 %6, i128 addrspace(200)* getelementptr inbounds (%struct.foo, %struct.foo addrspace(200)* @x, i32 0, i32 0), align 4
  ret i32 0
}

attributes #0 = { nounwind "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "stack-protector-buffer-size"="8" "target-features"="+cheri" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.ident = !{!0}

!0 = !{!"clang version 3.8.0 (https://github.com/CTSRD-CHERI/clang e66a25a5347f4739c87515f86495d98e1dd7b54b) (http://github.com/CTSRD-CHERI/llvm 6a7ed62359b6c4129499b8a9735fef977f71b6a1)"}

**Comment by davidchisnall** [comment]
This is now fixed in the merge branch.
