### ISSUE TITLE
LLVM crash while building CTSRD-CHERI/nginx

### ISSUE THREAD

**Issue by trasz** [CTSRD-CHERI/llvm#190]
While building nginx, clang crashes like this:

> 
> /home/trasz/cheri/output/sdk256/bin/clang -c -pipe --sysroot=/home/trasz/cheri/output/sdk256/sysroot -B/home/trasz/cheri/build/cheribsd-obj-256/mips.mips64/usr/home/trasz/cheri
> /cheribsd/tmp/usr/bin/ -target cheri-unknown-freebsd -mabi=sandbox -msoft-float -mxgot -O0 -G0 -static -integrated-as -Wcheri-capability-misuse -Werror=implicit-function-declaration -Werror=format -Werror=undefined-internal -I src/core  -I src/event  -I src/event/modules  -I src/os/unix  -I /usr/local/include  -I objs -I src/http  -I src/http/modules
>   -o objs/src/http/ngx_http.o  src/http/ngx_http.c
> /home/trasz/cheri/output/sdk256/bin/clang -c -pipe --sysroot=/home/trasz/cheri/output/sdk256/sysroot -B/home/trasz/cheri/build/cheribsd-obj-256/mips.mips64/usr/home/trasz/cheri
> /cheribsd/tmp/usr/bin/ -target cheri-unknown-freebsd -mabi=sandbox -msoft-float -mxgot -O0 -G0 -static -integrated-as -Wcheri-capability-misuse -Werror=implicit-function-declar
> ation -Werror=format -Werror=undefined-internal -I src/core  -I src/event  -I src/event/modules  -I src/os/unix  -I /usr/local/include  -I objs -I src/http  -I src/http/modules
>   -o objs/src/http/ngx_http_core_module.o  src/http/ngx_http_core_module.c
> fatal error: error in backend: Cannot select: 0x805d2f618: iFATPTR = add 0x805d2de38, 0x805d2f5b0
>   0x805d2de38: iFATPTR = PTRADD 0x805d2dd68, Constant:i64<3872>
>     0x805d2dd68: iFATPTR,ch = load<LD32[%6(addrspace=200)]> 0x805d2dd00, 0x805d2d3a8, undef:iFATPTR
>       0x805d2d3a8: iFATPTR = llvm.memcap.cap.bounds.set TargetConstant:i64<100>, 0x805d2d270, Constant:i64<32>
>         0x805d2d2d8: i64 = TargetConstant<100>
>         0x805d2d270: iFATPTR = llvm.mips.stack.to.cap TargetConstant:i64<2827>, FrameIndex:i64<0>
>           0x805d2d208: i64 = TargetConstant<2827>
>           0x805d2d1a0: i64 = FrameIndex<0>
>         0x805d2d340: i64 = Constant<32>
>       0x805d2d7b8: iFATPTR = undef
>     0x805d2ddd0: i64 = Constant<3872>
>   0x805d2f5b0: iFATPTR = INTTOPTR Constant:i64<8>
>     0x805d2f548: i64 = Constant<8>
> In function: ngx_http_handler
> clang-5.0: error: clang frontend command failed with exit code 70 (use -v to see invocation)
> clang version 5.0.0 (https://github.com/CTSRD-CHERI/clang.git 36fb1dc82f2552b06fa268eab5513cf52c16f41b) (https://github.com/CTSRD-CHERI/llvm.git 1888db97b2071c59f87f5b13ce6d560
> f956a392e)
> Target: cheri-unknown-freebsd
>

**Comment by davidchisnall** [comment]
Please attach the preprocessed source file that causes a crash (or, ideally, a reduced test case) and the minimal compile command to reproduce.

**Comment by trasz** [comment]
/home/en322/cheri/output/sdk256/bin/clang -c -target cheri-unknown-freebsd -mabi=sandbox -msoft-float -mxgot -O0 -G0 -static -integrated-as -Wcheri-capability-misuse -Werror=implicit-function-declaration -Werror=format -Werror=undefined-internal ngx_http_core_module-test.c

(Attached as txt; GitHub doesn't seem to support C files, huh.)

[ngx_http_core_module-test.c.txt](https://github.com/CTSRD-CHERI/llvm/files/799191/ngx_http_core_module-test.c.txt)

**Comment by trasz** [comment]
New, improved test case:

[ngx_http_core_module-test.c.txt](https://github.com/CTSRD-CHERI/llvm/files/799227/ngx_http_core_module-test.c.txt)

**Comment by davidchisnall** [comment]
Generally putting things in a gist works (and is easier to work with for me).  This test case appears to compile without crashing on the current merge branch.  Is it possible that this is a duplicate of #189, which was fixed yesterday?

**Comment by trasz** [comment]
Hm, I'll check that.

2017-02-24 12:34 GMT+00:00 davidchisnall <notifications@github.com>:

**Comment by trasz** [comment]
Yup, appears to be fixed.  Thanks!
