### ISSUE TITLE
Some weird atomics stuff.

### ISSUE THREAD

**Issue by trasz** [CTSRD-CHERI/llvm#194]
Happens with the merge-2017-01-18 LLVM branch.  Looks like this:

```
fatal error: error in backend: Cannot select: 0x805a812d8: i64 = bitcast 0x805a81340
  0x805a81340: iFATPTR,ch = CopyFromReg 0x80583d330, Register:iFATPTR %vreg1
    0x805a60ea0: iFATPTR = Register %vreg1
In function: atomic_flag_test_and_set_explicit
clang-5.0: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 5.0.0 (https://github.com/CTSRD-CHERI/clang.git 93993a232c59540cf838141008ef2da059d90c42) (https://github.com/CTSRD-CHERI/llvm.git 59e5c281cca155ac76ab834293b72fd6f8b81a42)
Target: cheri-unknown-freebsd
Thread model: posix
InstalledDir: /home/en322/cheri/output/sdk256/bin

```

To reproduce: build the attached file with "clang -mabi=sandbox  -target cheri-unknown-freebsd -c".

**Comment by trasz** [comment]
Attached file.

[test.c.txt](https://github.com/CTSRD-CHERI/llvm/files/810579/test.c.txt)

**Comment by davidchisnall** [comment]
Test case begins:

```
#include <stdatomic.h>
```

Is this the FreeBSD `stdatomic.h` or the clang one?  Please run this through the preprocessor and work out what it's expanding to (I'm guessing the `__c11_atomic_*` intrinsics?)

**Comment by trasz** [comment]
Indeed.  Expanded version is attached.

[test-E.c.txt](https://github.com/CTSRD-CHERI/llvm/files/810662/test-E.c.txt)

**Comment by davidchisnall** [comment]
This is a clang bug: CTSRD-CHERI/clang#118
