### ISSUE TITLE
Compiler crash with __asm__

### ISSUE THREAD

**Issue by trasz** [CTSRD-CHERI/llvm#195]
Trying to build one of the CheriOS files results in a frugal "Segmentation fault".   That file contains just a single __asm__... thing.

https://gist.github.com/trasz/486e0415c2e17a88f27915dbbd6d838b

**Comment by davidchisnall** [comment]
It appears as if `-mcpu=mips4` now implies not-CHERI, even for the CHERI triple.  This is probably not quite correct, as it would be nice to be able to treat CHERI as a set of extensions to any base CPU.

**Comment by davidchisnall** [comment]
This no longer crashes, but I'm seeing a strange issue now where the back end rejects the "C" constraint.  I thought @kgudka fixed some issues along those lines?

**Comment by arichardson** [comment]
This works fine now.
