### ISSUE TITLE
Pointer comparison yields surprising results.

### ISSUE THREAD

**Issue by trasz** [CTSRD-CHERI/llvm#199]
Comparing two pointers, one of which being 0xffffffffffffffff, leads to surprising results.

https://gist.github.com/trasz/ff494a5bad9aaab3b9e84b609397035d

**Comment by RichardsonAlex** [comment]
It seems like LLVM is outputting entirely sensible assembly, looks like QEMU is performing a signed comparison.

**Comment by RichardsonAlex** [comment]
Actually we are emitting a CLE, but I guess CLEU is the right instruction for pointer comparisons?

**Comment by davidchisnall** [comment]
It's not entirely clear.  `ptrdiff_t` is a signed quantity, which means that objects spanning the middle of the address space can lead to some interesting issues (not just on CHERI) and are generally discouraged.  It's a cleaner more consistent model to consider pointers to be signed, with kernel pointers all being negative.  That said, the IR generated here is clearly an unsigned comparison, so we should be matching CLEU, not CLE.

**Comment by davidchisnall** [comment]
Simpler test case:

```C
int lt(void*a, void*b)
{
	return a<b;
}
```

Becomes:

```LLVM
define i32 @lt(i8 addrspace(200)* readnone %a, i8 addrspace(200)* readnone %b) local_unnamed_addr #0 {
entry:
  %cmp = icmp ult i8 addrspace(200)* %a, %b
  %conv = zext i1 %cmp to i32
  ret i32 %conv
}
```

So far, so sensible.  This then becomes:

```asm
	daddiu	$sp, $sp, -32
	csd	$fp, $sp, 24($c11)
	move	 $fp, $sp
	cltu	$2, $c3, $c4             # <<< Unsigned less than
	move	 $sp, $fp
	cld	$fp, $sp, 24($c11)
	cjr	$c17
	daddiu	$sp, $sp, 32
```

So I'm not quite sure what the issue is.  Maybe a QEMU bug?

**Comment by trasz** [comment]
One more datapoint (suggested by Alex): if you change the 0xff..ff to 0x7f..ff, the problem does not occur.

**Comment by RichardsonAlex** [comment]
The interesting thing is that if I remove the call to puts() from the LLVM it correctly generates cltu, but if I leave it in then it uses CLE

**Comment by davidchisnall** [comment]
Actually, no they don't - `setugt` is being turned into `cltu` with the operands swapped, but should be `cleu` (`a > b` is equivalent to `b <= a`), but I don't think that would trigger this problem.

**Comment by RichardsonAlex** [comment]
For some reason the comparison is using `setoge` which then gets turned into a CLE32
