### ISSUE TITLE
UNREACHABLE when building hybrid binaries.

### ISSUE THREAD

**Issue by trasz** [CTSRD-CHERI/llvm#206]
UNREACHABLE executed at /home/en322/cheri/llvm/lib/Target/Mips/MipsOptimizePICCall.cpp:160!
#0 0x00000000048142cd llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/en322/cheri/llvm/lib/Support/Unix/Signals.inc:402:13
#1 0x0000000004738958 llvm::llvm_unreachable_internal(char const*, char const, unsigned int) /home/en322/cheri/llvm/lib/Support/ErrorHandling.cpp:123:3
#2 0x0000000002ce9e0d eraseGPOpnd(llvm::MachineInstr&) /home/en322/cheri/llvm/lib/Target/Mips/MipsOptimizePICCall.cpp:161:1
#3 0x0000000002ce941e (anonymous namespace)::OptimizePICCall::visitNode((anonymous namespace)::MBBInfo&) /home/en322/cheri/llvm/lib/Target/Mips/MipsOptimizePICCall.cpp:236:7
#4 0x0000000002ce8fe4 (anonymous namespace)::OptimizePICCall::runOnMachineFunction(llvm::MachineFunction&) /home/en322/cheri/llvm/lib/Target/Mips/MipsOptimizePICCall.cpp:201:16
#5 0x0000000003984041 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) /home/en322/cheri/llvm/lib/CodeGen/MachineFunctionPass.cpp:62:8
#6 0x0000000003e92a1f llvm::FPPassManager::runOnFunction(llvm::Function&) /home/en322/cheri/llvm/lib/IR/LegacyPassManager.cpp:1514:27
#7 0x0000000003e92d35 llvm::FPPassManager::runOnModule(llvm::Module&) /home/en322/cheri/llvm/lib/IR/LegacyPassManager.cpp:1536:16
#8 0x0000000003e93a38 (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /home/en322/cheri/llvm/lib/IR/LegacyPassManager.cpp:1592:27
#9 0x0000000003e92ff6 llvm::legacy::PassManagerImpl::run(llvm::Module&) /home/en322/cheri/llvm/lib/IR/LegacyPassManager.cpp:1695:16
#10 0x0000000003e94621 llvm::legacy::PassManager::run(llvm::Module&) /home/en322/cheri/llvm/lib/IR/LegacyPassManager.cpp:1726:3
#11 0x0000000004b6cb8b (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, clang::BackendAction::default_delete<llvm> >) /home/en322/cheri/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp:749:19
#12 0x0000000004b699cb clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, clang::LangOptions const&::Module*, clang::BackendAction, std::__1::unique_ptr<clang::LangOptions const&::raw_pwrite_stream, clang::BackendAction::default_delete<std::__1::unique_ptr> >) /home/en322/cheri/llvm/tools/clang/lib/CodeGen/BackendUtil.cpp:1018:15
#13 0x00000000056f87c8 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) /home/en322/cheri/llvm/tools/clang/lib/CodeGen/CodeGenAction.cpp:258:7
#14 0x0000000006b3a607 clang::ParseAST(clang::Sema&, bool, bool) /home/en322/cheri/llvm/tools/clang/lib/Parse/ParseAST.cpp:159:13
#15 0x000000000552bdb5 clang::ASTFrontendAction::ExecuteAction(void) /home/en322/cheri/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:613:1
#16 0x00000000056f3599 clang::CodeGenAction::ExecuteAction(void) /home/en322/cheri/llvm/tools/clang/lib/CodeGen/CodeGenAction.cpp:991:1
#17 0x000000000552b3a0 clang::FrontendAction::Execute(void) /home/en322/cheri/llvm/tools/clang/lib/Frontend/FrontendAction.cpp:516:7
#18 0x00000000053f916a clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/en322/cheri/llvm/tools/clang/lib/Frontend/CompilerInstance.cpp:951:7
#19 0x00000000056dce20 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/en322/cheri/llvm/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:249:8
#20 0x0000000001fd5e66 char const* cc1_main(llvm::ArrayRef<char const*>(void*) /home/en322/cheri/llvm/tools/clang/tools/driver/cc1_main.cpp:221:11
#21 0x0000000001fc58d9 llvm::StringRef ExecuteCC1Tool(llvm::ArrayRef<char const*>() /home/en322/cheri/llvm/tools/clang/tools/driver/driver.cpp:299:5
#22 0x0000000001fc34c1 main /home/en322/cheri/llvm/tools/clang/tools/driver/driver.cpp:380:5
#0 0x00000000048142cd llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/en322/cheri/llvm/lib/Support/Unix/Signals.inc:402:13
#1 0x0000000004814819 PrintStackTraceSignalHandler(void*) /home/en322/cheri/llvm/lib/Support/Unix/Signals.inc:498:1
#2 0x00000000048116e7 llvm::sys::RunSignalHandlers(void) /home/en322/cheri/llvm/lib/Support/Signals.cpp:45:5
#3 0x0000000004814b4a SignalHandler(int) /home/en322/cheri/llvm/lib/Support/Unix/Signals.inc:256:1
#4 0x0000000808b72784 handle_signal /usr/home/en322/svn/head/lib/libthr/thread/thr_sig.c:246:3
Stack dump:
0.      Program arguments: /usr/home/en322/cheri/output/sdk256/bin/clang-5.0 -cc1 -triple cheri-unknown-freebsd -emit-obj -disable-free -main-file-name ngx_http.c -static-define -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -target-cpu cheri -target-feature +soft-float -target-abi n64 -msoft-float -mfloat-abi soft -mllvm -mxgot -dwarf-column-info -debug-info-kind=standalone -dwarf-version=2 -debugger-tuning=gdb -coverage-notes-file /usr/home/en322/cheri/nginx/objs/src/http/ngx_http.gcno -O2 -Wcheri-capability-misuse -Werror=implicit-function-declaration -Werror=format -Werror=undefined-internal -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gnustep -fdiagnostics-show-option -vectorize-loops -vectorize-slp -cheri-linker -x c ngx_http-d09e82.c
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'ngx_http-d09e82.c'.
4.      Running pass 'Mips OptimizePICCall' on function '@ngx_http_create_locations_list'
Abort trap (core dumped)

https://gist.github.com/trasz/b3188bdb0da1dafb60a22219cfcbc12d

**Comment by RichardsonAlex** [comment]
Fixed in https://github.com/CTSRD-CHERI/llvm/commit/ef21e65bcfdeba4b01dc7372b4df4f723af00619
