### ISSUE TITLE
crash when compiling cherios

### ISSUE THREAD

**Issue by pmundkur** [CTSRD-CHERI/llvm#218]
I was trying to track down the lld failure in cherios using a toolchain from jenkins, but am seeing this crash with a cheribuild toolchain.

[101/150] /home/pm524/cheribuild/build/sdk256/bin/clang  -target cheri-unknown-freebsd  -I../include -I../include/sys -I../boot/include -I../uart/include -Iboot -mabi=purecap -cheri-linker -integrated-as -msoft-float -fcolor-diagnostics 
-fno-pic -v -mllvm -asm-macro-max-nesting-depth=100 -MD -MT boot/CMakeFiles/nano.dir/nanokernel/src/nano_kernel.S.o -MF boot/CMakeFiles/nano.dir/nanokernel/src/nano_kernel.S.o.d -o boot/CMakeFiles/nano.dir/nanokernel/src/nano_kernel.S.o 
-c /home/pm524/cheri/cherios/boot/nanokernel/src/nano_kernel.S
FAILED: boot/CMakeFiles/nano.dir/nanokernel/src/nano_kernel.S.o 
/home/pm524/cheribuild/build/sdk256/bin/clang  -target cheri-unknown-freebsd  -I../include -I../include/sys -I../boot/include -I../uart/include -Iboot -mabi=purecap -cheri-linker -integrated-as -msoft-float -fcolor-diagnostics -fno-pic -
v -mllvm -asm-macro-max-nesting-depth=100 -MD -MT boot/CMakeFiles/nano.dir/nanokernel/src/nano_kernel.S.o -MF boot/CMakeFiles/nano.dir/nanokernel/src/nano_kernel.S.o.d -o boot/CMakeFiles/nano.dir/nanokernel/src/nano_kernel.S.o -c /home/p
m524/cheri/cherios/boot/nanokernel/src/nano_kernel.S
clang version 5.0.0 (https://github.com/CTSRD-CHERI/clang.git e4a364866957989b3aab7cc9a4de2c1d1e4f6810) (https://github.com/CTSRD-CHERI/llvm.git 8f753461e6a5ce39222889807ce74d627aaa7c55)
Target: cheri-unknown-freebsd
Thread model: posix
InstalledDir: /home/pm524/cheribuild/build/sdk256/bin
 "/home/pm524/cheribuild/build/sdk256/bin/clang-5.0" -cc1 -triple cheri-unknown-freebsd -E -disable-free -main-file-name nano_kernel.S -mrelocation-model static -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -
target-cpu cheri -target-feature +soft-float -target-abi purecap -Wmips-cheri-prototypes -msoft-float -mfloat-abi soft -v -dwarf-column-info -debugger-tuning=gdb -coverage-notes-file /home/pm524/cheri/cherios/build/boot/CMakeFiles/nano.d
ir/nanokernel/src/nano_kernel.S.gcno -resource-dir /home/pm524/cheribuild/build/sdk256/lib/clang/5.0.0 -dependency-file boot/CMakeFiles/nano.dir/nanokernel/src/nano_kernel.S.o.d -sys-header-deps -MT boot/CMakeFiles/nano.dir/nanokernel/sr
c/nano_kernel.S.o -I ../include -I ../include/sys -I ../boot/include -I ../uart/include -I boot -isysroot /home/pm524/cheribuild/build/sdk256/sysroot -fdebug-compilation-dir /home/pm524/cheri/cherios/build -ferror-limit 19 -fmessage-leng
th 0 -fobjc-runtime=gnustep -fdiagnostics-show-option -fcolor-diagnostics -cheri-linker -mllvm -asm-macro-max-nesting-depth=100 -o /tmp/nano_kernel-33b36d.s -x assembler-with-cpp /home/pm524/cheri/cherios/boot/nanokernel/src/nano_kernel.
S
clang -cc1 version 5.0.0 based upon LLVM 5.0.0svn default target cheri-unknown-freebsd
#include "..." search starts here:
#include <...> search starts here:
 ../include
 ../include/sys
 ../boot/include
 ../uart/include
 boot
 /home/pm524/cheribuild/build/sdk256/lib/clang/5.0.0/include
 /home/pm524/cheribuild/build/sdk256/sysroot/usr/include
End of search list.
 "/home/pm524/cheribuild/build/sdk256/bin/clang-5.0" -cc1as -triple cheri-unknown-freebsd -filetype obj -main-file-name nano_kernel.S -target-cpu cheri -target-feature +soft-float -I ../include -I ../include/sys -I ../boot/include -I ../
uart/include -I boot -fdebug-compilation-dir /home/pm524/cheri/cherios/build -dwarf-debug-producer clang version 5.0.0 (https://github.com/CTSRD-CHERI/clang.git e4a364866957989b3aab7cc9a4de2c1d1e4f6810) (https://github.com/CTSRD-CHERI/ll
vm.git 8f753461e6a5ce39222889807ce74d627aaa7c55) -I ../include -I ../include/sys -I ../boot/include -I ../uart/include -I boot -dwarf-version=2 -mrelocation-model static -target-abi purecap -mllvm -asm-macro-max-nesting-depth=100 -o boot
/CMakeFiles/nano.dir/nanokernel/src/nano_kernel.S.o /tmp/nano_kernel-33b36d.s
Assertion failed: (ImmOp.isImm() && "expected immediate operand kind"), function expandLoadImm, file /home/pm524/cheribuild/sources/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp, line 2798.
#0 0x0000000004c32c9c llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/pm524/cheribuild/sources/llvm/lib/Support/Unix/Signals.inc:398:11
#1 0x0000000004c330e6 __assert /home/pm524/cheribuild/sources/llvm/lib/Support/Unix/Signals.inc:486:3
#2 0x000000000309db62 (anonymous namespace)::MipsAsmParser::expandLoadImm(llvm::MCInst&, bool, (anonymous namespace)::MipsAsmParser::expandLoadImm::SMLoc, (anonymous namespace)::MipsAsmParser::expandLoadImm::MCStreamer&, (anonymous names
pace)::MipsAsmParser::expandLoadImm::MCSubtargetInfo const*) /home/pm524/cheribuild/sources/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp:0:3
#3 0x000000000309c1fd (anonymous namespace)::MipsAsmParser::tryExpandInstruction(llvm::MCInst&, (anonymous namespace)::MipsAsmParser::tryExpandInstruction::SMLoc, (anonymous namespace)::MipsAsmParser::tryExpandInstruction::MCStreamer&, (
anonymous namespace)::MipsAsmParser::tryExpandInstruction::MCSubtargetInfo const*) /home/pm524/cheribuild/sources/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp:2314:12
#4 0x000000000308c30f (anonymous namespace)::MipsAsmParser::processInstruction(llvm::MCInst&, (anonymous namespace)::MipsAsmParser::processInstruction::SMLoc, (anonymous namespace)::MipsAsmParser::processInstruction::MCStreamer&, (anonym
ous namespace)::MipsAsmParser::processInstruction::MCSubtargetInfo const*) /home/pm524/cheribuild/sources/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp:2260:25
#5 0x0000000003056391 (anonymous namespace)::MipsAsmParser::MatchAndEmitInstruction(llvm::SMLoc, unsigned int&, (anonymous namespace)::MipsAsmParser::MatchAndEmitInstruction::SmallVectorImpl<std::__1::unique_ptr<(anonymous namespace)::Mi
psAsmParser::MatchAndEmitInstruction::MCParsedAsmOperand, (anonymous namespace)::MipsAsmParser::MatchAndEmitInstruction::SmallVectorImpl::default_delete<std::__1::unique_ptr> >>&, (anonymous namespace)::MipsAsmParser::MatchAndEmitInstruc
tion::MCStreamer&, unsigned long&, bool) /home/pm524/cheribuild/sources/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp:4723:9
#6 0x00000000047677c3 (anonymous namespace)::AsmParser::parseStatement((anonymous namespace)::ParseStatementInfo&, llvm::MCAsmParserSemaCallback*) /home/pm524/cheribuild/sources/llvm/lib/MC/MCParser/AsmParser.cpp:2065:9
#7 0x000000000475a8a4 (anonymous namespace)::AsmParser::Run(bool, bool) /home/pm524/cheribuild/sources/llvm/lib/MC/MCParser/AsmParser.cpp:762:9
#8 0x000000000222b116 ExecuteAssembler((anonymous namespace)::AssemblerInvocation&, clang::DiagnosticsEngine&) /home/pm524/cheribuild/sources/llvm/tools/clang/tools/driver/cc1as_main.cpp:442:12
#9 0x0000000002220410 char const* cc1as_main(llvm::ArrayRef<char const*>(void*) /home/pm524/cheribuild/sources/llvm/tools/clang/tools/driver/cc1as_main.cpp:522:45
#10 0x0000000002209a9b llvm::StringRef ExecuteCC1Tool(llvm::ArrayRef<char const*>() /home/pm524/cheribuild/sources/llvm/tools/clang/tools/driver/driver.cpp:301:5
#11 0x00000000022074a4 main /home/pm524/cheribuild/sources/llvm/tools/clang/tools/driver/driver.cpp:380:5
#12 0x000000000220617f _start (/home/pm524/cheribuild/build/sdk256/bin/clang-5.0+0x220617f)
#0 0x0000000004c32c9c llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/pm524/cheribuild/sources/llvm/lib/Support/Unix/Signals.inc:398:11
#1 0x0000000004c33169 PrintStackTraceSignalHandler(void*) /home/pm524/cheribuild/sources/llvm/lib/Support/Unix/Signals.inc:494:1
#2 0x0000000004c30067 llvm::sys::RunSignalHandlers(void) /home/pm524/cheribuild/sources/llvm/lib/Support/Signals.cpp:0:5
#3 0x0000000004c3349a SignalHandler(int) /home/pm524/cheribuild/sources/llvm/lib/Support/Unix/Signals.inc:252:1
#4 0x0000000808fd278f (/lib/libthr.so.3+0xe78f)
#5 0x0000000808fd1d6f (/lib/libthr.so.3+0xdd6f)
Stack dump:
0.      Program arguments: /home/pm524/cheribuild/build/sdk256/bin/clang-5.0 -cc1as -triple cheri-unknown-freebsd -filetype obj -main-file-name nano_kernel.S -target-cpu cheri -target-feature +soft-float -I ../include -I ../include/sys -
I ../boot/include -I ../uart/include -I boot -fdebug-compilation-dir /home/pm524/cheri/cherios/build -dwarf-debug-producer clang version 5.0.0 (https://github.com/CTSRD-CHERI/clang.git e4a364866957989b3aab7cc9a4de2c1d1e4f6810) (https://g
ithub.com/CTSRD-CHERI/llvm.git 8f753461e6a5ce39222889807ce74d627aaa7c55) -I ../include -I ../include/sys -I ../boot/include -I ../uart/include -I boot -dwarf-version=2 -mrelocation-model static -target-abi purecap -mllvm -asm-macro-max-n
esting-depth=100 -o boot/CMakeFiles/nano.dir/nanokernel/src/nano_kernel.S.o /tmp/nano_kernel-33b36d.s 
clang-5.0: error: unable to execute command: Abort trap (core dumped)
clang-5.0: error: clang integrated assembler command failed due to signal (use -v to see invocation)
clang version 5.0.0 (https://github.com/CTSRD-CHERI/clang.git e4a364866957989b3aab7cc9a4de2c1d1e4f6810) (https://github.com/CTSRD-CHERI/llvm.git 8f753461e6a5ce39222889807ce74d627aaa7c55)
Target: cheri-unknown-freebsd
Thread model: posix
InstalledDir: /home/pm524/cheribuild/build/sdk256/bin
clang-5.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-5.0: note: diagnostic msg: 
********************
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-5.0: note: diagnostic msg: /tmp/nano_kernel-ed91e3.S
clang-5.0: note: diagnostic msg: /tmp/nano_kernel-ed91e3.sh
clang-5.0: note: diagnostic msg: 

[nano_kernel-ed91e3.S.txt](https://github.com/CTSRD-CHERI/llvm/files/991214/nano_kernel-ed91e3.S.txt)
[nano_kernel-ed91e3.sh.txt](https://github.com/CTSRD-CHERI/llvm/files/991215/nano_kernel-ed91e3.sh.txt)

**Comment by arichardson** [comment]
This reproducer no longer crashes.
