### ISSUE TITLE
Throwing exceptions in C++ doesn't work on MIPS

### ISSUE THREAD

**Issue by bsdjhb** [CTSRD-CHERI/llvm#229]
I was investigating the crashes when running a recently compiled gdb as noted in https://github.com/bsdjhb/gdb/issues/3 and discovered that gdb was crashing when it tried to catch an exception.  I then wrote a simple C++ test that tried to throw two exceptions, one an int, and the other a simple struct with two fields.  When I compile this with a clang-built CheriBSD world and run it it seg faults trying to catch the struct:

root@cheri:~ # /mnt/cppexcept/./a.out
x = 0
Bus error (core dumped)

The value of 'x' in the first printf is also wrong (should be 4).

**Comment by bsdjhb** [comment]
#include <exception>
#include <stdio.h>

struct Foo {
        Foo(int v, const char *s) : value(v), msg(s) {}
        int value;
        const char *msg;
};

int
main()
{

        try {
                throw 4;
        } catch (int x) {
                printf("x = %d\n", x);
        }

        try {
                throw Foo(42, "oh well");
        } catch (Foo &f) {
                printf("value = %d, msg = \"%s\"\n", f.value, f.msg);
        }

        return (0);
}

**Comment by davidchisnall** [comment]
I don't believe that this is an LLVM bug, as I am able to compile code with LLVM linked against libunwind and libcxxrt and both throw and catch exceptions on MIPS.  I suspect that this is an an issue with the libgcc_s in base.  Replacing that with the CheriBSD libunwind ought to work, as I implemented and tested the MIPS64 code paths there before starting to work on the CHERI ones.

**Comment by bsdjhb** [comment]
With the fix in [b6090e9c4df65be4a7f8c633b41bb6a316a56694](https://github.com/CTSRD-CHERI/libunwind/commit/b6090e9c4df65be4a7f8c633b41bb6a316a56694) I can now throw simple objects like an int.  However, throwing a more complex type like a struct does not work.

I get a crash in the landing zone because the pointer to the 'Foo' object is bogus.  I tracked this down to a problem in check_type_signature() called from check_action_record() during phase 1.  The code that fails in check_type_signature():

```
	const std::type_info *ex_type = ex ? ex->exceptionType : 0;

	bool is_ptr = ex ? ex_type->__is_pointer_p() : false;
```

When throwing an int this correctly calls the base '__is_pointer_p()' which returns false:

```
(gdb) s
check_type_signature (ex=<optimized out>, type=0x401ab3b0 <typeinfo for int>, 
    adjustedPtr=<optimized out>)
    at /usr/home/john/work/cheri/git/cheribsd/contrib/libcxxrt/exception.cc:933
933             const std::type_info *ex_type = ex ? ex->exceptionType : 0;
...
(gdb) x/i $pc
=> 0x401939d8 <check_action_record(_Unwind_Context*, dwarf_eh_lsda*, unsigned char*, __cxxabiv1::__cxa_exception*, unsigned long*, void*&)+360>:  jalr    t9
   0x401939dc <check_action_record(_Unwind_Context*, dwarf_eh_lsda*, unsigned char*, __cxxabiv1::__cxa_exception*, unsigned long*, void*&)+364>:  move    a0,s1
(gdb) p/x $t9
$64 = 0x40185408
(gdb) x/4i $t9
   0x40185408 <std::type_info::__is_pointer_p() const>: daddiu  sp,sp,-16
   0x4018540c <std::type_info::__is_pointer_p() const+4>:       sd      s8,8(sp)
   0x40185410 <std::type_info::__is_pointer_p() const+8>:       move    s8,sp
   0x40185414 <std::type_info::__is_pointer_p() const+12>:      li      v0,0
(gdb) 
   0x40185418 <std::type_info::__is_pointer_p() const+16>:      move    sp,s8
   0x4018541c <std::type_info::__is_pointer_p() const+20>:      ld      s8,8(sp)
   0x40185420 <std::type_info::__is_pointer_p() const+24>:      jr      ra
   0x40185424 <std::type_info::__is_pointer_p() const+28>:      daddiu  sp,sp,16
(gdb) ni
936             if (is_ptr)
(gdb) p/x $v0
$65 = 0x0
```

However, when throwing a 'struct Foo' the call to __is_pointer_p() calls the destructor which leaves garbage in 'v0':

```
(gdb) s
check_type_signature (ex=<optimized out>, type=0x40028 <typeinfo for Foo>, adjustedPtr=<optimized out>)
    at /usr/home/john/work/cheri/git/cheribsd/contrib/libcxxrt/exception.cc:933
933             const std::type_info *ex_type = ex ? ex->exceptionType : 0;
(gdb) p *$ex->exceptionType
$77 = {_vptr$type_info = 0x401ab978 <vtable for __cxxabiv1::__class_type_info>, __type_name = 0x102ec <typeinfo name for Foo> "3Foo"}
...
# Loading vptr of type_info:
(gdb) x/i $pc
=> 0x401939d0 <check_action_record(_Unwind_Context*, dwarf_eh_lsda*, unsigned char*, __cxxabiv1::__cxa_exception*, unsigned long*, void*&)+352>:  ld      at,0(s1)
(gdb) si
0x00000000401939d4      935             bool is_ptr = ex ? ex_type->__is_pointer_p() : false;
(gdb) p/x$at
$78 = 0x401ab978
# Loading __is_pointer_p function pointer
(gdb) x/i $pc
=> 0x401939d4 <check_action_record(_Unwind_Context*, dwarf_eh_lsda*, unsigned char*, __cxxabiv1::__cxa_exception*, unsigned long*, void*&)+356>:  ld      t9,16(at)
(gdb) si
0x00000000401939d8      935             bool is_ptr = ex ? ex_type->__is_pointer_p() : false;
(gdb) p/x $t9
$81 = 0x40184e30
(gdb) x/i $t9
   0x40184e30 <std::type_info::~type_info()>:   daddiu  sp,sp,-16
# Dumping the vtable for the 'Foo' type_info:
(gdb) x/4gx 0x401ab978         
0x401ab978 <vtable for __cxxabiv1::__class_type_info>:  0x0000000000000000      0x00000000401ab9c0
0x401ab988 <vtable for __cxxabiv1::__class_type_info+16>:       0x0000000040184e30      0x0000000040185108
(gdb) 
0x401ab998 <vtable for __cxxabiv1::__class_type_info+32>:       0x0000000040185408      0x0000000040185428
0x401ab9a8 <vtable for __cxxabiv1::__class_type_info+48>:       0x0000000040194f30      0x0000000040185488
# The "right" pointer is at offset '32', not the '16' the instruction was expecting:
(gdb) x/i 0x0000000040185408
   0x40185408 <std::type_info::__is_pointer_p() const>: daddiu  sp,sp,-16
```

From this last, I noticed that in the typeinfo for 'int', the _vptr points to an offset of 16 beyond the type_info object:

```
(gdb) p *(std::type_info *)$s1
$85 = {_vptr$type_info = 0x401ab090 <vtable for __cxxabiv1::__fundamental_type_info+16>, 
  __type_name = 0x40196128 <typeinfo name for int> "i"}
```

However, in the typeinfo for 'Foo', the _vptr points at the start of the type_info object.  If it were +16 like 'int' then it would be correct:

```
(gdb) p *(std::type_info *)0x40028
warning: can't find linker symbol for virtual table for `std::type_info' value
warning:   found `typeinfo for __cxxabiv1::__enum_type_info' instead
$86 = warning: can't find linker symbol for virtual table for `std::type_info' value
warning:   found `typeinfo for __cxxabiv1::__enum_type_info' instead
{_vptr$type_info = 0x401ab978 <vtable for __cxxabiv1::__class_type_info>, __type_name = 0x102ec <typeinfo name for Foo> "3Foo"}
```
I did link the binary with lld in this case though the "world" was built with ld.bfd.  Trying to link with ld.bfd fails, but I wonder if perhaps lld is "losing" the +16 in the relocation to construct the _vptr for the Foo typeinfo object?

**Comment by bsdjhb** [comment]
Note that if I compile the object file and look at the relocations I see this relocation record for the 'Foo' typeinfo:

```
RELOCATION RECORDS FOR [.data.rel.ro._ZTI3Foo]:
OFFSET           TYPE              VALUE 
0000000000000000 R_MIPS_64         vtable for __cxxabiv1::__class_type_info+0x0000000000000010
0000000000000000 R_MIPS_NONE       *ABS*+0x0000000000000010
0000000000000000 R_MIPS_NONE       *ABS*+0x0000000000000010
0000000000000008 R_MIPS_64         typeinfo name for Foo
0000000000000008 R_MIPS_NONE       *ABS*
0000000000000008 R_MIPS_NONE       *ABS*
```

The corresponding relocation in the binary doesn't appear to show the +0x10 offset?

```
> mips64-freebsd-objdump -R a.out | c++filt

a.out:     file format elf64-tradbigmips-freebsd

DYNAMIC RELOCATION RECORDS
OFFSET           TYPE              VALUE 
0000000000030028 R_MIPS_REL32      typeinfo for int@CXXABI_1.3
0000000000030028 R_MIPS_64         *ABS*
0000000000030028 R_MIPS_NONE       *ABS*
0000000000040028 R_MIPS_REL32      vtable for __cxxabiv1::__class_type_info@CXXABI_1.3
0000000000040028 R_MIPS_64         *ABS*
0000000000040028 R_MIPS_NONE       *ABS*
0000000000030030 R_MIPS_REL32      __gxx_personality_v0@CXXABI_1.3
0000000000030030 R_MIPS_64         *ABS*
0000000000030030 R_MIPS_NONE       *ABS*
```

**Comment by bsdjhb** [comment]
I tried this change, but it did not help:

```
diff --git a/ELF/Target.cpp b/ELF/Target.cpp
index ceb5e0730..5ff930e7d 100644
--- a/ELF/Target.cpp
+++ b/ELF/Target.cpp
@@ -2291,6 +2291,8 @@ int64_t MipsTargetInfo<ELFT>::getImplicitAddend(const uint8_t *Buf,
   case R_MIPS_TLS_DTPREL32:
   case R_MIPS_TLS_TPREL32:
     return SignExtend64<32>(read32<E>(Buf));
+  case R_MIPS_64:
+    return read64<E>(Buf);
   case R_MIPS_26:
     // FIXME (simon): If the relocation target symbol is not a PLT entry
     // we should use another expression for calculation:
```

(The .o file has many other R_MIPS_64 with addends, so presumably this must be working via some other means I don't see?)

**Comment by RichardsonAlex** [comment]
Clang emits object files with RELA relocations so there should be no need to call getImplicitAddend (unless there is some ld -r invocation in the build system).

The patch makes sense to me. I think the reason that  it has not been a problem is that we probably never end up in that switch statement because all our MIPS object files have RELA relocations. Might be worth adding an assert to that branch to see whether it is actually being used.

**Comment by bsdjhb** [comment]
I've not been able to link my test program with ld.bfd btw because both old and new ld.bfd keep reporting a missing "std::get_new_handler' symbol. Yet the lld-linked binary finds the symbol in libcxxrt.so.1:

```
Temporary breakpoint 1, main () at cppexcept.cpp:36
36              some_function();
(gdb) x/i std::get_new_handler
   0x401912a0 <std::get_new_handler()>: daddiu  sp,sp,-16
```

In the libcxxrt.so.1 that I have from my build, the function doesn't show up in the symbol tables displayed by readelf or nm, but somehow lld is able to link against it?  I can't even find the string for the symbol name using strings against libcxxrt.so.1, so this is really confusing.

**Comment by bsdjhb** [comment]
Alex's [hack](https://github.com/CTSRD-CHERI/lld/commit/9e279b8c353743e02acf7e1eb3b6a3f3813a0b66) to lld to handle REL addends fixed my exception test case using a structure when linking via lld.
