### ISSUE TITLE
Need a way to disable PIC behavior for assembly files under CheriABI

### ISSUE THREAD

**Issue by Jerryxia32** [CTSRD-CHERI/llvm#231]
In some implementations of CheriOS where even the kernel is compiled in CheriABI, many PIC patches make writing kernel assembly painful and almost impossible. The root cause is that PIC is compulsory under CheriABI and many assembly instructions are rewritten (namely `j` and `dla`).

As an example, it means that even writing a relocatable kernel exception trampoline is particularly painful: writing `j __kernel_handler` will be turned into `b __kernel_handler` which often fails due to smaller immediate, and a `dla $k0, __kernel_handler; jr $k0` sequence still does not work due to PIC dla. I have forced all assembly files to be non-PIC but linking them against CheriABI C files produces ABI mismatch warnings and is a very ugly hack I think. It also forces me to insert $gp prologues where unnecessary in the kernel.

It would be really helpful to have a switch to turn off PIC in assembly files under CheriABI, or CheriABI can compile in non-PIC, but I think the latter is harder.

**Comment by bsdjhb** [comment]
You can use '.option pic0' to disable PIC code generation within a single assembly file.  If you need to re-enable it you can use '.option pic2'.  For some asm stubs used in hybrid code I just ended up disabling it for the entire file: https://github.com/CTSRD-CHERI/cheribsd/commit/97525be04390a0ad8502dfbbc0a6c2113baaf9e0

**Comment by RichardsonAlex** [comment]
Why can't you use -fno-pic? For assembly files it should work as expected. It is only a problem when compiling c code.

**Comment by Jerryxia32** [comment]
The .option pic0/2 pair is exactly what I need. I want PIC disabled for some parts of the assembly but not entirely. This also does not affect the PIC flag of the compiled object file from the assembly, preventing linking warnings. Thanks.
