### ISSUE TITLE
Int in a union passed as variadic gets wrong value.

### ISSUE THREAD

**Issue by trasz** [CTSRD-CHERI/llvm#232]
On CHERI-128, when passing an int via union as variadic parameter to a function - like it's being done with semctl(2) - the int value is wrong.  Testcase:

https://gist.github.com/trasz/aa4015846b9fc60adfba911fb5c70d75

**Comment by davidchisnall** [comment]
Clang bug.

**Comment by kgudka** [comment]
This is an LLVM bug.
