### ISSUE TITLE
Dynamic TLS passes tls_info in $a0 instead of $c3 for purecap mode

### ISSUE THREAD

**Issue by bsdjhb** [CTSRD-CHERI/llvm#233]
I get a crash in dynamically-linked /bin/helloworld now when __cxa_thread_call_dtors runs as an atexit hook.  This function uses a TLS variable that holds a per-thread list of destructors to run on exit.  As a dynamic binary, this calls __tls_get_addr() to resolve the address of the TLS variable.  __tls_get_addr() expects to be passed a pointer to a 'tls_index' structure.  The function entry from rtld is:

```
void *
__tls_get_addr(tls_index* ti)
{
	...
}
```

The address of a given tls_index is stored as an address in the GOT.  Currently LLVM is fetching that address and then passing it in $a0 instead of $c3 in purecap mode (done here in the branch delay slot):

```
   0x1725b0 <__cxa_thread_call_dtors+64>:       lui     at,0x0
   0x1725b4 <__cxa_thread_call_dtors+68>:       daddu   at,at,gp
   0x1725b8 <__cxa_thread_call_dtors+72>:       ld      at,-18776(at)
   0x1725bc <__cxa_thread_call_dtors+76>:       cgetpccsetoffset        $c12,at
   0x1725c0 <__cxa_thread_call_dtors+80>:       cjalr   $c12,$c17
   0x1725c4 <__cxa_thread_call_dtors+84>:       daddiu  a0,gp,-13832
```

This needs to be passing a valid pointer in $c3 instead.  The code that generates this call to __tls_get_addr() is in MipsTargetLowering::lowerGlobalTLSAddress in lib/Target/Mips/MipsISelLowering.cpp.  At present I suspect that the GOT entry just holds a flat address of the tls_index structure rather than a capability, so for now the code gen should probably be loading the address from the GOT and then constructing a capability from $ddc?

One workaround I can pursue for now is to patch __tls_get_addr() in the CHERI ABI rtld to assume it's argument is a vaddr instead of a pointer.

**Comment by bsdjhb** [comment]
Related to this is that the generated code assumes the return pointer from tls_get_addr is returned in $v0 instead of a capability register.

**Comment by bsdjhb** [comment]
I also realized I only ran into this because I am testing changes to centralize workarounds for clang on MIPS not selecting the right TLS model and had disabled the CFLAGS change to force local-exec TLS for WANT_CHERI.  My current hack to rtld to make __tls_get_addr work with vaddr_t's instead of pointers does seem to work if we would prefer that model to forcing local-exec.

**Comment by davidchisnall** [comment]
The fix for this is nontrivial, as it involves modifying some of the MI codegen layer to emit GlobalTLSAddress objects with iFATPTR types.  I think it's probably not worth doing until we have a sensible model for TLS.

**Comment by bsdjhb** [comment]
Ok.  FWIW, I don't think we will change this part of the TLS model, but any changes to handle TLS (e.g. per-compartment TLS) will be done in the implementation of __tls_get_addr.  For non-dynamic TLS I suspect we will change the thread pointer register (hwr $29 on MIPS) as part of a compartment switch (which might also make the existing __tls_get_addr() logic already work since it is just determining offsets relative to TP).

**Comment by davidchisnall** [comment]
I think that, for pure-cap mode, we'll want to replace hwr $29 with a capability version, but I'm then not sure whether we'll want to pre-populate that with bounded capabilities, or whether we'll want to dynamically apply the bounds on load.  Currently, `__tls_get_addr` is returning an offset, but it might be cleaner if it returned a bounded capability.

**Comment by arichardson** [comment]
This should be fixed.
