### ISSUE TITLE
CHERI128 is allocating 32-bytes per capability register

### ISSUE THREAD

**Issue by jonwoodruff** [CTSRD-CHERI/llvm#255]
The following function when compiled for cheri128, cheriabi:
/local/scratch/jdw57/sdk128/bin/clang -mcpu=cheri128 -mabi=purecap -c -target cheri-unknown-freebsd -integrated-as -S -o out.s quickSort.c  -O3 -ffunction-sections -fomit-frame-pointer
```
void quickSort( int a[], int l, int r)
{
   int j;

   if( l < r ) 
   {
   	// divide and conquer
       //j = partition( a, l, r);
       int pivot, i, j, t;
			 pivot = a[l];
			 i = l; j = r+1;
		
			 while( 1)
			 {
			 	do ++i; while( a[i] <= pivot && i <= r );
			 	do --j; while( a[j] > pivot );
			 	if( i >= j ) break;
			 	t = a[i]; a[i] = a[j]; a[j] = t;
			 }
			 t = a[l]; a[l] = a[j]; a[j] = t;
       quickSort( a, l, j-1);
       quickSort( a, j+1, r);
   }
}
```
Has this stack spill:
```
	cincoffset	$c11, $c11, -144
	csd	$gp, $zero, 136($c11)   # 8-byte Folded Spill
	csd	$19, $zero, 128($c11)   # 8-byte Folded Spill
	csd	$18, $zero, 120($c11)   # 8-byte Folded Spill
	csd	$17, $zero, 112($c11)   # 8-byte Folded Spill
	csd	$16, $zero, 104($c11)   # 8-byte Folded Spill
	csc	$c19, $zero, 64($c11)   # 32-byte Folded Spill
	csc	$c18, $zero, 32($c11)   # 32-byte Folded Spill
	csc	$c17, $zero, 0($c11)    # 32-byte Folded Spill
```

**Comment by davidchisnall** [comment]
What happens if you add `-mllvm -cheri128`?

**Comment by jonwoodruff** [comment]
Looks the same with those flags added.

**Comment by davidchisnall** [comment]
Actually, even without that, I can't reproduce this with my cheri128 clang.  Simply with `clang -S -o - -O1 spill.c  -mabi=purecap`, I get:

```asm
        cincoffset      $c11, $c11, -112
        csd     $gp, $zero, 104($c11)   # 8-byte Folded Spill
        csd     $19, $zero, 96($c11)    # 8-byte Folded Spill
        csd     $18, $zero, 88($c11)    # 8-byte Folded Spill
        csd     $17, $zero, 80($c11)    # 8-byte Folded Spill
        csd     $16, $zero, 72($c11)    # 8-byte Folded Spill
        csc     $c24, $zero, 48($c11)   # 16-byte Folded Spill
        csc     $c19, $zero, 32($c11)   # 16-byte Folded Spill
        csc     $c18, $zero, 16($c11)   # 16-byte Folded Spill
        csc     $c17, $zero, 0($c11)    # 16-byte Folded Spill
```

**Comment by jonwoodruff** [comment]
Maybe this indicates that Jenkins isn't building the compiler correctly in the end?

**Comment by davidchisnall** [comment]
It really looks as if you've built a 256-bit clang and you're trying to compile 128-bit code for it.  What happens if you remove all cheri128 flags?

**Comment by jonwoodruff** [comment]
/local/scratch/jdw57/sdk128/bin/clang -mabi=purecap -c -target cheri-unknown-freebsd -integrated-as -S -o out.s quickSort.c  -O3 -ffunction-sections -fomit-frame-pointer

Does not report any errors.  Is it possible that Jenkins is building a 256-bit compiler and calling it 128-bit?

**Comment by davidchisnall** [comment]
> Does not report any errors.

If it's a 128-bit compiler, it should.

> Is it possible that Jenkins is building a 256-bit compiler and calling it 128-bit?

Yes.

> Actually, this seems very unlikely since we were seeing 16-byte stack allocations for capabilities allocated as local variables.

No, that's *exactly* what happens currently with a 256-bit compiler when passed -cheri128 (though it should abort if you didn't pass the magic test flag)

**Comment by Jerryxia32** [comment]
I am cloning the most recent source and building 128. On my machine, I am seeing the same 32-byte stack spill. The compiler I am using should be the 128 compiler because it crashes when trying to pass -mcpu=cheri instead of -mcpu=cheri128. The ELF flag also shows that this is a cheri128 binary.

**Comment by davidchisnall** [comment]
I'm on the nosp branch, so it looks as if this was something broken by the upstream merge?

**Comment by davidchisnall** [comment]
Actually, no.  Updating to the latest master, I get the same thing:

```
        cincoffset      $c11, $c11, -96
        csd     $gp, $zero, 88($c11)    # 8-byte Folded Spill
        csd     $19, $zero, 80($c11)    # 8-byte Folded Spill
        csd     $18, $zero, 72($c11)    # 8-byte Folded Spill
        csd     $17, $zero, 64($c11)    # 8-byte Folded Spill
        csd     $16, $zero, 56($c11)    # 8-byte Folded Spill
        csc     $c19, $zero, 32($c11)   # 16-byte Folded Spill
        csc     $c18, $zero, 16($c11)   # 16-byte Folded Spill
        csc     $c17, $zero, 0($c11)    # 16-byte Folded Spill
```

So I think that you are building the CHERI128 compiler incorrectly.

**Comment by RichardsonAlex** [comment]
I can reproduce this with a recent build of LLVM

**Comment by RichardsonAlex** [comment]
And it is definitely a 128 compiler: `target datalayout = "E-m:e-pf200:128:128-i8:8:32-i16:16:32-i64:64-n32:64-S128-A200"`

**Comment by davidchisnall** [comment]
I've just done a new build of master, and I cannot reproduce this.  The compiler is built by the build_sdk.sh script.

**Comment by RichardsonAlex** [comment]
Actually, I just rebuilt master and I can't reproduce it anymore.

**Comment by Jerryxia32** [comment]
Strange. I can reliably reproduce the problem on a Linux machine but fail to see it on a FreeBSD machine.
