### ISSUE TITLE
insane division sequence with sufficiently complex code

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#258]
This bit of code:
```C
extern int TermH;   
extern int didfds;
int isatty(int);  
void afunc(int);
int returnanint(void);

void
print_by_column(int *items[], int count, int no_file_suffix)
{
    int i, columns, rows;
    unsigned int maxwidth;    

    maxwidth = returnanint();

    maxwidth += no_file_suffix ? 1 : 2;
    columns = TermH / maxwidth;
    if (!columns || !isatty(didfds))
         columns = 1;
    rows = (count + (columns - 1)) / columns;

    afunc(rows); // retain liveness of rows
}
```
Compiled with:
```
clang -g -integrated-as --target=cheri-unknown-freebsd -cheri=128 -mabi=purecap -msoft-float -O  -c tw.parse.i -S -o tw.parse.s
```
produces this delightfully insane bit of assembly:
```ASM
2453:   divu    $zero, $3, $2
2473-   mflo    $1
2482-   csw     $1, $zero, 8($c24)      # 8-byte Folded Spill
2533-   mfhi    $1
2542-   csw     $1, $zero, 8($c24)      # 8-byte Folded Spill
```
Later on, the result is restored as `columns` and inevitably results in a divide by zero and trap.

**Comment by brooksdavis** [comment]
Note this occurs at `-O`, `-O1`, and `-O2` but not without any `-O` flags.

**Comment by brooksdavis** [comment]
this remains broken after recent llvm updates

**Comment by arichardson** [comment]
Is it also broken when targeting MIPS?

**Comment by brooksdavis** [comment]
No, csh works as expected.

**Comment by arichardson** [comment]
I can still reproduce this in both master and dev but for some reason only when compiling the source code with clang. If I do an -emit-llvm and compile it with llc it won't emit the strange sequence.

**Comment by davidchisnall** [comment]
If I understand correctly, the issue is that we're spilling two different registers to the same stack slot, but only for CHERI?  There may be an issue with generating CHERI spills in the back end, though it's surprising that it would be triggered only here.  Perhaps it's the only place that we're spilling `%hi` and `%lo`?

**Comment by davidchisnall** [comment]
The generic code is allocating one FrameIndex to store the accumulator register (LLVM models `%hi` and `%lo` as a single register, which is not quite optimal) and we end up with spills at FI+0 and FI+4.  I *think* that we're then ignoring the offset when we do the `FrameIndex` lowering.
