### ISSUE TITLE
Padding considered part of struct

### ISSUE THREAD

**Issue by jonwoodruff** [CTSRD-CHERI/llvm#262]
Padding is added explicitly to structs in purecap mode, and the padding seems to be actively propagated.  This is the prime suspect for generating lots of 12-byte regions that are propagated in duktape.

C source:

```C
%struct.name_t = type { i8*, i32 }

; Function Attrs: nounwind
define noalias %struct.name_t* @test(i32 signext %select, %struct.name_t* nocapture readonly %inA, i8* nocapture readnone %cp) local_unnamed_addr #0 {
entry:
typedef struct {
	char *dub;
	int  in;
} name_t;

extern void func(name_t inA);

#define SIZE 1

name_t * test(int select, name_t *inA, char *cp)
{	
	func(*inA);
        return (void *)0;
}
```

MIPS:
```LLVM
 %0 = bitcast %struct.name_t* %inA to i64*
  %1 = load i64, i64* %0, align 8
  %2 = getelementptr inbounds %struct.name_t, %struct.name_t* %inA, i64 0, i32 1
  %3 = bitcast i32* %2 to i64*
  %4 = load i64, i64* %3, align 8
  tail call void @func(i64 inreg %1, i64 inreg %4) #2
```

CHERI:

```LLVM
%struct.name_t = type { i8 addrspace(200)*, i32, [12 x i8] }

; Function Attrs: nounwind
define noalias %struct.name_t addrspace(200)* @test(i32 signext %select, %struct.name_t addrspace(200)* nocapture readonly %inA, i8 addrspace(200)* nocapture readnone %cp) local_unnamed_addr #0 {
entry:
  %0 = getelementptr inbounds %struct.name_t, %struct.name_t addrspace(200)* %inA, i64 0, i32 0
  %1 = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %0, align 16
  %2 = getelementptr inbounds %struct.name_t, %struct.name_t addrspace(200)* %inA, i64 0, i32 1
  %3 = bitcast i32 addrspace(200)* %2 to i64 addrspace(200)*
  %4 = load i64, i64 addrspace(200)* %3, align 16
  %5 = getelementptr inbounds %struct.name_t, %struct.name_t addrspace(200)* %inA, i64 0, i32 2, i64 4
  %6 = bitcast i8 addrspace(200)* %5 to i64 addrspace(200)*
  %7 = load i64, i64 addrspace(200)* %6, align 8
  tail call void @func(i8 addrspace(200)* inreg %1, i64 inreg %4, i64 inreg %7) #2
```

The issue is that when name_t is passed by value, the last 64-bits of padding is loaded and allocated a dedicated register. This appears to be caused by a change to the definition of the struct that makes the padding explicit in CHERI ([12 x i8]).

This appears to cause much more interesting issues when lots of such structs with padding are handled.  We have a function in DukTape with 9 "alloca"s of [12 x i8] align 4 which appear to come from padding in various structs which are then memcopied about as normal loads and stores wouldn't easily do the trick.  Obviously we shouldn't care if these are copied at all.

**Comment by davidchisnall** [comment]
It's not clear to me that this is a bug.  Clang pads structures explicitly in a number of places, because LLVM's notion of a structure is not the same as C's.

**Comment by Jerryxia32** [comment]
I think what Jon is saying is that in the above example MIPS does not pad the structure explicitly (at least in the IR struct definition it seems) while CHERI does, and this might be a source of performance overhead. Also even if explicit padding is done for MIPS, the padding never exceeds the size of a general purpose register, but for CHERI the padding could be as large as 31 bytes for CHERI-256 which means when passing by value there could be an additional 3 general purpose registers involved just to pass the padding. We are wondering if there is something that could be done to avoid this overhead.

**Comment by arichardson** [comment]
My guess is that the struct is being padded because the alignment is now more than alingof(Address space 0 pointer).

**Comment by davidchisnall** [comment]
That's my guess as well.  I'm not sure what the default alignment of LLVM struct types is, but I think it's not huge.

There's an upstream bug tracking a related issue, that the front end doesn't have any mechanism for telling LLVM that a struct field is padding, so it must treat all fields as real data.  SROA should help with this in theory, because it should split the struct into the three fields and later passes will discover that the padding field is never used.  I'm not sure why this isn't happening here.

**Comment by arichardson** [comment]
I think it is because func() takes the struct by value so clang emits a function that takes 3 arguments (taking the padding into account). Since it is an external function it doesn't know that the rest of the struct is padding so has to pass it along 👎

**Comment by davidchisnall** [comment]
I'm a bit surprised this is external, since all of duktape is in one compilation unit, but I'd agree - we can't eliminate the padding, because it's part of the ABI, and we don't have enough expressiveness in LLVM IR to indicate that it's padding.

**Comment by jonwoodruff** [comment]
The "external" thing was just a trick to keep this from being optimised away.  The behaviour we've seen in Duktape is simply that copying structs that end in a uint32 involve copying fields of the struct and then copying 12 bytes with memcpy.  Furthermore, the capability and uint32 are converted to registers using sroa, but the 12-byte paddings are all allocated on the stack and handled separately.  One solution would be the compiler copying uint32 with the padding using a capability copy.

**Comment by davidchisnall** [comment]
Please can you put the original thing in the bug tracker?

> Furthermore, the capability and uint32 are converted to registers using sroa

That is expected

> but the 12-byte paddings are all allocated on the stack and handled separately

That is exactly what the result of SROA is supposed to do.

> Furthermore, the capability and uint32 are converted to registers using sroa, but the 12-byte paddings are all allocated on the stack and handled separately

That's also expected, because arrays in SSA registers are problematic (immutable arrays are not fun).

The problem is that the operations on the padding are not being removed.  In this case, it's because something else is using the entire struct.  

> One solution would be the compiler copying uint32 with the padding using a capability copy.

I wonder if just padding with 12 `i8`s rather than a `[12 x i8]` would be better.

**Comment by davidchisnall** [comment]
After some discussions with Peter Sewell, it doesn't look possible to fix this without breaking C semantics.
