### ISSUE TITLE
Defining functions with 9+ capability arguments broken

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/llvm#264]
Since d7dfe7ad380132ed08a49352bf96319737d30122 it is no longer possible to compile openssl in cheribsd. The machine verifier (for some reason on by default in clang?) complains about using an undefined register (c13).

Reduced test case (See test/CodeGen/Mips/cheri/bn_x931p-regression.ll)
```
define i32 @a(i64 addrspace(200) *, i32 addrspace(200) *, i32 addrspace(200) *,
              i64 addrspace(200) *, i64 addrspace(200) *, i64 addrspace(200) *,
              i32 addrspace(200) *, i32 addrspace(200) *, i32 addrspace(200) *) {
  %ret = call i32 @b()
  ret i32 %ret
}

declare i32 @b()
```

**Comment by davidchisnall** [comment]
Fixed, by just deleting this tiny optimisation.
