### ISSUE TITLE
Cannot select due to "Rework memory operation lowering"

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/llvm#265]
CheriBSD no longer compiles with the latest clang. The reduced test case (`test/CodeGen/Mips/cheri/lzma_index_regression.ll`) is a single call to memcpy so it is probably caused by https://github.com/CTSRD-CHERI/llvm/commit/1331be47d5a4c9ef34fda3f39c5af3689443e403 .

**Comment by davidchisnall** [comment]
Interesting.  It seems to die when emitting a 24-byte memcpy for a 16-byte-aligned thing.  I suspect that the problem here is that it tries the unaligned overlapping thing that it shouldn't be allowed to do.
