### ISSUE TITLE
Compiler crashes on cast.

### ISSUE THREAD

**Issue by qwattash** [CTSRD-CHERI/llvm#272]
While updating the purecap kernel I encountered a crash after an incompatible pointer type warning in vfs_aio.c. The kernel is being compiled in the pure capability ABI.

The following line seems to be causing the problem in the source code:

```
error = kern_mlock(job->userproc, job->cred, (__cheri_addr uintptr_t)
         __DEVOLATILE_CAP(void * __capability, cb->aio_buf), cb->aio_nbytes);
```
The following seems to workaround the crash:
```
error = kern_mlock(job->userproc, job->cred, (uintptr_t)
       __DEVOLATILE_CAP(void * __capability, cb->aio_buf), cb->aio_nbytes);`
```
reduced test case: [here](https://gist.github.com/qwattash/a69dde5d509b7abffa932f74232e307a)

**Comment by arichardson** [comment]
Looking at the code I'm not sure whether we should actually make this an error.
```
#define a(b, c) (b)0
typedef __uintcap_t d;
e() { (__cheri_addr d) a(void *, ); }
```
@kgudka: I'm not sure it makes sense to use __cheri_addr with uintcap_t since it will give an i64.

**Comment by qwattash** [comment]
I think that it makes sense to have an error, if we wanted a virtual address we should use an i64 type, if we wanted a pointer type we could just leave the cast to uintptr_t.

**Comment by bsdjhb** [comment]
I believe I might have tripped over this today in my naivete trying to extract the virtual address from a capability in hybrid code.  My offending line was:

```
		ur.handle = (void *)(__cheri_addr uintptr_t)rc->handle;
```

The goal in this case was to extract the virtual address and store it in a plain C pointer.  It reduced to this:

```
typedef __uintcap_t uintcap_t struct {
  uintcap_t a
} b = (__cheri_addr uintptr_t)b->a
```

**Comment by arichardson** [comment]
__cheri_* casts on uintcap_t should be working now.
