### ISSUE TITLE
Unable to call c++ virtual function 

### ISSUE THREAD

**Issue by minight** [CTSRD-CHERI/llvm#281]
The following program throws a cheri fault on line 21 (`return (object->*method)();`) when attempting to call the virtual function of a class. This was compiled with `clang++ --sysroot=<cheripath>/cheri/output/sdk/sysroot128 -B<cheripath>/cheri/output/sdk -msoft-float --target=cheri-unknown-freebsd virtualfunction.cpp -mabi=purecap -O1` running on CheriBSD. 

The source code was extracted from the googletest codebase.

The program compiles and runs fine on -O2 however fails on -O1 and -O0. I’m currently compiling with github.com/CTSRD_CHERI/llvm commit 34023badfac256f4b3ec3bff138598b82be2c799. 

I appreciate any help or guidance you would be able to provide with this.

```
#include <cheri.h>
#include <cstdint>
#include <stdio.h>
#include <stdlib.h>

class TestFactoryBase {
public:
  virtual void *CreateTest() {};
};

class TestFactoryImpl : public TestFactoryBase {
public:
  void *CreateTest() override {
    printf("CreateTest called\n");
    return nullptr;
  }
};

void *HandleExceptionsInMethodIfSupported(TestFactoryBase *object,
                                          void *(TestFactoryBase::*method)()) {
  return (object->*method)();
}

int main(int argc, char *argv[]) {
  TestFactoryBase *factory = new TestFactoryImpl();
  HandleExceptionsInMethodIfSupported(factory, &TestFactoryBase::CreateTest);
  return 0;
}
```

**Comment by arichardson** [comment]
If I compile this minimal test case at -O2 `printf()` (or rather `puts()` since the compiler optimizes the printf call) is called directly instead of HandleExceptionsInMethodIfSupported() thereby bypassing the pointer-to-virtual member function call.
It is possible that recent merges have broken virtual pointer-to-member calls.

**Comment by arichardson** [comment]
I can't reproduce this with latest LLVM/Clang/LLD/CheriBSD master. So it seems like this has been fixed.

**Comment by minight** [comment]
Thanks Alex. I can confirm that the latest build of LLVM resolves the issue. There appears to a separate issue with googletest now however I'll file a report when I root cause the issue.
