### ISSUE TITLE
bgeu not implemented

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#81]
```
/home/bed22/git/cheribsd/lib/libc/mips/sys/brk.S:59:2: error: Unknown instruction
 bgeu $4, $2, 1f
 ^
```

**Comment by brooksdavis** [comment]
see mips run documents this as

bgeu s,t,label =>
sltu at,s,t
beq at,$zero,offs

**Comment by emaste** [comment]
Patch in review upstream http://reviews.llvm.org/D8537

**Comment by davidchisnall** [comment]
Should be fixed in the next merge.  Please tests and close if it is (once the merge is committed).
