### ISSUE TITLE
__attribute__ ((aligned)) yields 8 byte alignments

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#85]
__attribute__ ((aligned)) produces 8-bit alignment in non-sandbox CHERI code.  The GCC docs say it should produce the maximum useful alignment which is 32-bytes.  The one reason we might want to leave it alone is that it presumably does change the ABI.

**Comment by davidchisnall** [comment]
Should we set this to 32 for the pure-capability ABI?

**Comment by brooksdavis** [comment]
Yeah, we should presumably set it to sizeof(void *)
