### ISSUE TITLE
ternary operator with function pointer and NULL requiring unnecessary cast

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#93]
This code https://gist.github.com/brooksdavis/382643cb676e226342d4 compiles without warning in clang, but gives a type mismatch in the sandbox ABI:

{{{
$ /home/bed22/git/llvm-cheri/Build/bin/clang -integrated-as --target=cheri-unknown-freebsd -msoft-float --sysroot=/home/bed22/obj/mips.mips64/home/bed22/git/cheribsd/tmp -mabi=sandbox -c func-cast.c -o /dev/null
func-cast.c:10:16: warning: pointer type mismatch ('int
      (*)(__attribute__((address_space(200))) int)' and
      '__attribute__((address_space(200))) void *') [-Wpointer-type-mismatch]
        func = x == 0 ? foo : NULL;
                      ^ ~~~   ~~~~
1 warning generated.
}}}

A cast works around this, but tcpdump likes many-argument functions without typedefs so refactoring to add a typedef is often required.

**Comment by davidchisnall** [comment]
I am not sure about this.  It appears that you are expecting (void*)0 to be a valid function pointer without a cast.  This is undefined behaviour by the C standard and not supported with the sandbox ABI because function pointers are integers (implicitly PCC-relative), whereas void* is a capability.

**Comment by brooksdavis** [comment]
If I tweak the code to just assign NULL to func, then there is no warning so I think this is special to the ternary-if sanity checking code.  If we aren't going to support this, than some sort of NULL_FP definition might be useful.  The standard probably should have one if NULL isn't a valid thing to assign to a function pointer.

**Comment by davidchisnall** [comment]
We get a warning there, but also an error on the if statement.  It's generally better to use 0, rather than NULL, for function pointers, as it will be implicitly cast to the correct type.  This compiles correctly if NULL is replaced with 0.

**Comment by davidchisnall** [comment]
Fixed (clang issue).
