### ISSUE TITLE
Cast from pointer to unsigned int

### ISSUE THREAD

**Issue by michael-roe** [CTSRD-CHERI/llvm#94]
A cast from a pointer to an unsigned int can result in MIPS opcodes whose behaviour is undefined according to the MIPS ISA (32 bit operation on a value that is not the sign extension of a 32 bit value).

Example C code:
static int HashRange = 16;

int hashfunc(unsigned int key)
{
  return ((key>>4) % HashRange);
}

/***** in separate compilation unit ******/
#include <stdint.h>

extern int hashfunc(unsigned int key);

static void *y = (void *) 0x801005d0;

int test(void)
{
int x;

  x = hashfunc((unsigned int) y);

  return 0;
}

===============
 ModuleID = 'test_clang_cast.c'
target datalayout = "E-m:m-p200:256:256-i8:8:32-i16:16:32-i64:64-n32:64-S128"
target triple = "cheri-unknown-freebsd"

; Function Attrs: nounwind
define i32 @test() #0 {
  %1 = tail call i32 @hashfunc(i32 zeroext -2146433584) #2
  ret i32 0
}

declare i32 @hashfunc(i32 zeroext) #1

attributes #0 = { nounwind "less-precise-fpmad"="false" "no-frame-pointer-elim"
="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-nans-fp-
math"="false" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-s
oft-float"="false" }
attributes #1 = { "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "
no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-nans-fp-math"="fa
lse" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float
"="false" }
attributes #2 = { nobuiltin nounwind }

!llvm.ident = !{!0}
======
Compiled with -O1 -ffreestanding

**Comment by davidchisnall** [comment]
Please report this upstream.
