### ISSUE TITLE
clang-3.6: error: argument unused during compilation: '-mllvm -cheri8'

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#97]
-mllvm -cheri8 should be ignored when linking, but is not and results in an error.

**Comment by davidchisnall** [comment]
There's a general policy in clang to not silently accept arguments that have no meaning in a particular context.  It's difficult to silence this one, because it's an LLVM flag not a clang one, so it doesn't go via the normal command-line parsing logic that delegates to the toolchains.
