### ISSUE TITLE
static initializers for arrays of structs take non linear time to compile

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm#98]
for an array like:

'''C
typedef struct {
    uint32_t code;
    const char *name;
} nt_err_code_struct;

/*
 * NT Error codes
 */
static const nt_err_code_struct nt_errors[] = {  
  { 0x00000000, "STATUS_SUCCESS" },
  { 0x00000000, "STATUS_WAIT_0" },
...
  { 0, NULL }
};
'''

The compiler take an amount of time which increases super linearly with the number of elements.  This gist contains runtimes from different array sizes when compiling contrib/tcpdump/smbutil.c. https://gist.github.com/brooksdavis/2e5061ae83d8398282db

**Comment by davidchisnall** [comment]
We're now memoising these, so compile time should be much faster (log(n) in terms of the number of struct types used in initialisers, rather than n*m in terms of the number of struct fields and the number of declarations)
